all-versions:
- 3.0.3.1
- 3.0.3.2
- 4.0.0.0
- 4.1.0.0
- 4.2.0.0
- 4.2.0.1
- 4.2.0.2
- 4.3.0.0
- 4.3.1.0
- 4.4.0.0
- 4.4.1.0
- 4.5.0.0
- 4.5.1.0
- 4.6.0.0
- 4.6.0.1
- 4.7.0.0
- 4.7.0.1
- 4.7.0.2
- 4.8.0.0
- 4.8.1.0
- 4.8.2.0
- 4.9.0.0
- 4.9.1.0
- 4.10.0.0
- 4.10.1.0
- 4.11.0.0
- 4.11.1.0
- 4.12.0.0
- 4.13.0.0
- 4.14.0.0
- 4.14.1.0
- 4.14.2.0
- 4.14.3.0
- 4.15.0.0
- 4.15.1.0
- 4.16.0.0
- 4.16.1.0
- 4.16.2.0
- 4.16.3.0
- 4.16.4.0
- 4.17.0.0
- 4.17.1.0
- 4.17.2.0
- 4.17.2.1
- 4.18.0.0
- 4.18.1.0
- 4.18.2.0
- 4.18.2.1
- 4.19.0.0
- 4.19.1.0
- 4.20.0.0
author: ''
basic-deps:
  ghc-internal: '>=9.1001 && <9.1002'
  ghc-prim: '>=0'
changelog: ''
changelog-type: ''
description: |-
  Haskell's base library provides, among other things, core types (e.g. [Bool]("Data.Bool") and [Int]("Data.Int")),
  data structures (e.g. [List]("Data.List"), [Tuple]("Data.Tuple") and [Maybe]("Data.Maybe")),
  the [Exception]("Control.Exception") mechanism, and the [IO]("System.IO") & [Concurrency]("Control.Concurrent") operations.
  The "Prelude" module, which is imported by default, exposes a curated set of types and functions from other modules.

  Other data structures like [Map](https://hackage.haskell.org/package/containers/docs/Data-Map.html),
  [Set](https://hackage.haskell.org/package/containers/docs/Data-Set.html) are available in the [containers](https://hackage.haskell.org/package/containers) library.
  To work with textual data, use the [text](https://hackage.haskell.org/package/text/docs/Data-Text.html) library.
description-type: haddock
hash: 6b1ae61e45db82289a287b0bb1fc689c3b418d97bffe8e226df23d60e7967405
homepage: ''
latest: 4.20.0.0
license-name: BSD-3-Clause
maintainer: Core Libraries Committee <core-libraries-committee@haskell.org>
synopsis: Core data structures and operations
test-bench-deps: {}
