all-versions:
- 0.0.0.0
author: Cary Robbins
basic-deps:
  aeson: '>=1.5.6.0 && <2'
  base: '>=4.7 && <5'
  bytestring: '>=0.10.12.0 && <1'
  file-embed: '>=0.0.15.0 && <1'
  template-haskell: '>=2.16.0.0 && <3'
  yaml: '>=0.11.8.0 && <1'
changelog: |
  # Changelog for embed-config

  ## 0.0.0.0

  * First release
changelog-type: markdown
description: |
  # embed-config [![embed-config](https://img.shields.io/hackage/v/embed-config.svg?logo=haskell&color=blueviolet)](https://hackage.haskell.org/package/embed-config)

  Reasonable conventions for embedding YAML configuration with Template Haskell

  ## Quick Start

  **config/settings.yml**
  ```yaml
  foo-bar: 42
  baz-quux: hello
  ```

  **src/MyApp/Config.hs**
  ```haskell
  module MyApp.Config where

  import Data.Yaml.Config.Embed (AesonKebab(..), embedConfig)

  loadConfig :: IO Config
  loadConfig = $(embedConfig)

  data Config = Config
    { fooBar :: Int
    , bazQuux :: String
    } deriving stock (Show, Eq, Generic)
      deriving (FromJSON) via AesonKebab Config
  ```
description-type: markdown
hash: 71b2a48bfad8b717bad6165dc6795c1baa400db21549e7eeff5b41e978be2199
homepage: https://github.com/simspace/embed-config#readme
latest: 0.0.0.0
license-name: BSD-3-Clause
maintainer: carymrobbins@gmail.com
synopsis: Reasonable conventions for embedding YAML configuration with Template Haskell
test-bench-deps:
  aeson: '>=0'
  base: '>=4.7 && <5'
  embed-config: '>=0'
  hspec: '>=0'
