all-versions:
- '0.1'
- 0.1.0.2
author: Yoshikuni Jujo
basic-deps:
  base: '>=4 && <5'
  directory: '>=0'
  filepath: '>=0'
  process: '>=0'
  unix: '>=0'
changelog: ''
changelog-type: ''
description: |-
  I inspired by xmonad. Xmonad is configurable by using user's own main.
  This package make your application configurable like xmonad.
description-type: haddock
hash: ab3264ebf799e07e40fd913b9061197b346a7d84145908566155231e62a45c02
homepage: http://github.com/YoshikuniJujo/hsConfigure/wiki
latest: 0.1.0.2
license-name: LicenseRef-LGPL
maintainer: Yoshikuni Jujo <PAF01143@nifty.ne.jp>
synopsis: By using this package, you can make application configurable.
test-bench-deps: {}
