all-versions:
- 0.1.0
- 0.1.1
- 0.1.2
- 0.1.3
author: Junji Hashimoto
basic-deps:
  aeson: '>=0'
  base: '>=4 && <5'
  bytestring: '>=0'
  containers: '>=0'
  directory: '>=0'
  hastache: '>=0'
  http-conduit: '>=0'
  lifted-base: '>=0'
  network: '>=0'
  optparse-applicative: '>=0'
  process: '>=0'
  shelly: '>=0'
  test-sandbox: '>=0.1'
  test-sandbox-compose: '>=0'
  text: '>=0'
  unix: '>=0'
  wai: '>=0'
  wai-extra: '>=0'
  warp: '>=0'
  yaml: '>=0'
  yesod: '>=0'
  yesod-core: '>=0'
changelog: |
  ## 0.1.3

  * Add lauching order directive for config file(yaml)

  ## 0.1.2

  * Update cabal-test (remove setup for running daemon)

  ## 0.1.1

  * Fix Changelog.md
changelog-type: markdown
description: |
  # Test-Sandbox-Compose: Fast Development Environments Using Test-Sandbox

  [![Hackage version](https://img.shields.io/hackage/v/test-sandbox-compose.svg?style=flat)](https://hackage.haskell.org/package/test-sandbox-compose)  [![Build Status](https://travis-ci.org/junjihashimoto/test-sandbox-compose.png?branch=master)](https://travis-ci.org/junjihashimoto/test-sandbox-compose)

  Test-Sandbox-Compose makes development environments for multi-servers using Test-Sandbox.
  Each server is defined in test-sandbox-compose.yml.
  test-sandbox-compose.yml provides following functions.

  * Mustache template for accessing each resource
  * Before/After-bash-script for server-setup
  * Tempolary file, directory and TCP-Port which test-sandbox provides

  This project is inspired by Docker Compose(Fig).

  ## Getting started

  Install this from Hackage.

      cabal update && cabal install test-sandbox-compose


  ## test-sandbox-compose.yml reference

  ```
  <service-name1>:
    cmd: <command-name>
    args:
      - <arg1>
      - <arg2>
    confs:
      <conf1>: <conf1 contents>
      <conf2>: <conf2 contents>
    tempfiles:
      - <temp1>
      - <temp2>
    dirs:
      - <dir1>
      - <dir2>
    ports:
      - <port1>
      - <port2>
    beforescript: <script content>
    afterscript: <script content>
  <service-name2>
    ...
  ```

  Example

  ```
  zookeeper:
    cmd: '/usr/share/zookeeper/bin/zkServer.sh'
    args:
      - 'start-foreground'
      - '{{zookeeper_conf_conf}}'
    tempfiles: []
    confs:
      conf: |
        dataDir={{zookeeper_dir_data}}
        clientPort={{zookeeper_port_2181}}
        maxClientCnxns=1000
    dirs:
      - 'data'
    ports:
      - '2181'
  ```


  ## Commands


  ### Up

  ```
  test-sandbox-compose up
  ```

  ### Status

  ```
  test-sandbox-compose status
  ```

  ### Conf

  ```
  test-sandbox-compose conf
  ```

  ### Kill

  ```
  test-sandbox-compose kill
  ```

  ### Logs

  ```
  test-sandbox-compose logs
  ```

  ### Destroy

  ```
  test-sandbox-compose destroy
  ```

  ### Daemon

  ```
  test-sandbox-compose daemon
  ```
description-type: markdown
hash: 52c2bd3ae55c1e4d605a7f9516693f810f8a37582c27b1944397d6a162a4c658
homepage: ''
latest: 0.1.3
license-name: BSD-3-Clause
maintainer: junji.hashimoto@gmail.com
synopsis: Lightweight development enviroments using test-sandbox
test-bench-deps:
  base: '>=4 && <5'
  bytestring: '>=0'
  cabal-test-bin: '>=0.1.4'
  hspec: '>=0'
  hspec-test-sandbox: '>=0'
  process: '>=0'
  shakespeare: '>=0'
  test-sandbox: '>=0'
  text: '>=0'
  unix: '>=0'
