all-versions:
- 1.0.0
- 1.1.0
- 1.2.0
- 1.3.0
- 1.4.0
- 1.4.1
- 2.1.0
- 2.2.0
- 3.0.0
- 3.0.1
- 3.0.2
- 3.0.3
- 3.0.4
- 3.0.5
author: John Wiegley, Roy Blankman
basic-deps:
  base: '>=3 && <5'
  binary: '>=0.5.1.1'
  bytestring: '>=0.9.2.1'
  fast-logger: '>=2.1.5'
  lifted-base: '>=0.2.2.0'
  monad-control: '>=0.3.2.3'
  old-locale: '>=1.0.0.5'
  regex-compat: '>=0.95.1'
  text: '>=0.11.3.1'
  time: '>=1.4'
  time-locale-compat: '>=0.1.1.0'
  transformers: '>=0.3.0.0'
changelog: ''
changelog-type: ''
description: |-
  @logging@ is a wrapper around @fast-logger@ which makes
  it easy to log from 'IO'. It provides the following conveniences on top of
  those libraries:

  - A set of shorter functions to type: 'debug', 'log', 'warn', plus others
  that flush after each message, or which allow providing a message source
  string.

  - Logging variants of 'error', 'trace' and 'traceShow', called 'errorL',
  'traceL' and 'traceShowL'.  These use 'unsafePerformIO' in order to act as
  direct replacements, so the usual caveats apply.

  - A global function, 'setDebugLevel', which uses a global 'IORef' to record
  the logging level, saving you from having to carry around the notion of
  "verbosity level" in a Reader environment.

  - A set of "timed" variants, 'timedLog' and 'timedDebug', which report how
  long the specified action took to execute in wall-clock time.
description-type: haddock
hash: 88096d3124fce9a19af3720f751e1a354d866ed5030d2e5197238d2277cdb2f2
homepage: ''
latest: 3.0.5
license-name: MIT
maintainer: riblankman@gmail.com
synopsis: Simplified logging in IO for application writers.
test-bench-deps:
  base: '>=0'
  hspec: '>=1.4'
  logging: '>=0'
  unix: '>=2.5.1.1'
