all-versions:
- 0.1.0
- 0.2.0
author: Composewell Technologies and Contributors
basic-deps:
  base: '>=4.7 && <4.19'
  unicode-data: '>=0.4 && <0.5'
changelog: |
  # Changelog

  ## 0.2.0 (September 2022)

  - Update to [Unicode 15.0.0](https://www.unicode.org/versions/Unicode15.0.0/).

  ## 0.1.0 (September 2022)

  - Initial release
changelog-type: markdown
description: |
  # README

  `unicode-data-security` provides Haskell APIs to efficiently access the
  [Unicode security mechanisms](https://www.unicode.org/reports/tr39/)
  [database](https://www.unicode.org/Public/security/).

  The Haskell data structures are generated programmatically from the
  Unicode character database (UCD) files. The latest Unicode version
  supported by this library is
  [`15.0.0`](https://www.unicode.org/versions/Unicode15.0.0/).

  Please see the
  [Haddock documentation](https://hackage.haskell.org/package/unicode-data-security)
  for reference documentation.

  ## Licensing

  `unicode-data-security` is an [open source](https://github.com/composewell/unicode-data)
  project available under a liberal [Apache-2.0 license](LICENSE).

  ## Contributing

  As an open project we welcome contributions.
description-type: markdown
hash: 0f930b6a663716d0e3bad30a86c3d8751e6a306a7ce39defa74cea687df97a55
homepage: http://github.com/composewell/unicode-data
latest: 0.2.0
license-name: Apache-2.0
maintainer: dev@wismill.eu
synopsis: Unicode security mechanisms database
test-bench-deps:
  base: '>=4.7 && <4.19'
  deepseq: '>=1.1 && <1.5'
  hspec: '>=2.0 && <2.11'
  tasty: '>=1.4.1'
  tasty-bench: '>=0.2.5 && <0.4'
  unicode-data-security: '>=0'
