all-versions:
- 0.1.0
- 0.2.0
- 0.3.0
- 0.4.0
- 0.5.0
- 0.6.0
author: Composewell Technologies and Contributors
basic-deps:
  base: '>=4.7 && <4.23'
  ghc-prim: '>=0.3.1 && <1.0'
  unicode-data: '>=0.8 && <0.9'
changelog: |
  # Changelog

  ## 0.6.0 (September 2025)

  - Updated to [Unicode 17.0.0](https://www.unicode.org/versions/Unicode17.0.0/).

  ## 0.5.0 (September 2025)

  - Updated to [Unicode 16.0.0](https://www.unicode.org/versions/Unicode16.0.0/).

  ## 0.4.0 (July 2024)

  - Updated to [Unicode 15.1.0](https://www.unicode.org/versions/Unicode15.1.0/).

  ## 0.3.0 (July 2024)

  - Changed the type of `confusablePrototype` and `intentionalConfusables` from
    `Char -> Maybe String` to `Char -> String`.
  - Added `unicodeVersion` to `Unicode.Char.Identifiers.Security`.
  - Fixed the inlining of `Addr#` literals and reduce their size. This results in
    a sensible decrease of the executable size.

  ## 0.2.0 (September 2022)

  - Updated to [Unicode 15.0.0](https://www.unicode.org/versions/Unicode15.0.0/).

  ## 0.1.0 (September 2022)

  - Initial release
changelog-type: markdown
description: |
  # README

  `unicode-data-security` provides Haskell APIs to efficiently access the
  [Unicode security mechanisms](https://www.unicode.org/reports/tr39/)
  [database](https://www.unicode.org/Public/security/).

  The Haskell data structures are generated programmatically from the
  Unicode character database (UCD) files. The latest Unicode version
  supported by this library is
  [`17.0.0`](https://www.unicode.org/versions/Unicode17.0.0/).

  Please see the
  [Haddock documentation](https://hackage.haskell.org/package/unicode-data-security)
  for reference documentation.

  ## Licensing

  `unicode-data-security` is an [open source](https://github.com/composewell/unicode-data)
  project available under a liberal [Apache-2.0 license](LICENSE).

  ## Contributing

  As an open project we welcome contributions.
description-type: markdown
hash: e83263e546f0a636a6462479f2fa3547f641dcdcb636a83f3a234a611ea93820
homepage: http://github.com/composewell/unicode-data
latest: 0.6.0
license-name: Apache-2.0
maintainer: dev@wismill.eu
synopsis: Unicode security mechanisms database
test-bench-deps:
  base: '>=4.7 && <4.23'
  deepseq: '>=1.1 && <1.6'
  hspec: '>=2.0 && <2.12'
  tasty: '>=1.4.1'
  tasty-bench: '>=0.2.5 && <0.5'
  unicode-data-security: '>=0'
