all-versions:
- 0.3.1
- 0.3.2
- 0.3.3
author: ''
basic-deps:
  aeson: '>=0'
  base: '>=4.7 && <5'
  data-default: '>=0'
  random: '>=0'
  string-conversions: '>=0'
  text: '>=0'
  unordered-containers: '>=0'
  vault: '>=0'
  yaml: '>=0'
changelog: ''
changelog-type: ''
description: |
  # yam-config
description-type: markdown
hash: dddd7daf109632367d9e564c90d83782555b9d26d424b2133c1d3ff943cdd1a3
homepage: https://github.com/leptonyu/yam#readme
latest: 0.3.3
license-name: MIT
maintainer: Daniel YU <leptonyu@gmail.com>
synopsis: Yam Configuation
test-bench-deps: {}
