homepage: ''
changelog-type: ''
hash: ed0c2f343d0ef32fe1941e42c0a3ec4e78befda79a65530ce161ef3374db9f40
test-bench-deps:
  base: '>=4.5.0 && <5.0.0'
  unordered-containers: '>=0.2.0'
  text: '>=0.11.0'
  tasty-quickcheck: '>=0.8.0'
  hashable: '>=1.2.0'
  tasty: '>=0.10.0'
  deepseq: '>=1.3'
  QuickCheck: '>=2.6.0'
  yaml: '>=0.8.10'
maintainer: mitroshin@selectel.org
synopsis: Configuration management
changelog: ''
basic-deps:
  base: '>=4.5.0 && <5.0.0'
  unordered-containers: '>=0.2.0'
  text: '>=0.11.0'
  deepseq: '>=1.3'
  yaml: '>=0.8.10 && <0.11.7'
all-versions:
- 0.0.1
- 0.1.0
- 0.2.0
- 0.2.1
- 0.2.2
- 0.2.3
- 0.3.0
- 0.4.0
author: |-
  Fedor Gogolev <knsd@knsd.net>
  Mitroshin Maxim <mitroshin@selectel.org>
  Simon Hengel <sol@typeful.net>
latest: 0.4.0
description-type: haddock
description: Configuration management
license-name: MIT
