all-versions:
- 0.1.0.0
- 0.1.0.1
- 0.1.1.0
- 0.1.1.1
- 0.2.0.0
- 0.2.0.1
- 0.3.0.0
- 0.3.0.1
- 0.4.0.0
author: Adrian Cochrane
basic-deps:
  base: '>=4.12 && <5'
  containers: '>=0.1 && <1'
  css-syntax: '>=0'
  fontconfig-pure: '>=0'
  freetype2: '>=0.2 && <0.3'
  hashable: '>=1.3 && <2'
  linear: '>=1.0.1 && <2'
  scientific: '>=0'
  stylist-traits: '>=0.1.1 && <1'
  text: '>=0'
changelog: |
  # Revision history for fontconfig-pure

  ## 0.3.0.0 -- 2023-10-01

  * Addressing segfaults & mainloops.
  * Switched underlying CharSet collection to IntSet for efficiency.

  ## 0.1.0.0 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
changelog-type: markdown
description: Resolves font descriptions to font libraries, including ones installed
  on your freedesktop (Linux or BSD system).
description-type: haddock
hash: 4935bf6bdf6e48d178b1069c79baad99b7ec9631e49a865f73d9a74f97817bb1
homepage: https://www.freedesktop.org/wiki/Software/fontconfig/
latest: 0.4.0.0
license-name: MIT
maintainer: adrian@openwork.nz
synopsis: Pure-functional language bindings to FontConfig
test-bench-deps:
  QuickCheck: '>=0'
  base: '>=4.12 && <5'
  fontconfig-pure: '>=0'
  hspec: '>=0'
