all-versions:
- 0.1.0.0
- 0.1.0.1
- 0.1.1.0
- 0.1.1.1
- 0.2.0.0
- 0.2.0.1
- 0.3.0.0
- 0.3.0.1
- 0.4.0.0
- 0.5.0.0
author: Adrian Cochrane
basic-deps:
  QuickCheck: '>=0'
  base: '>=4.17.0.0 && <4.18'
  bytestring: '>=0'
  containers: '>=0.1 && <1'
  css-syntax: '>=0'
  fontconfig-pure: '>=0'
  freetype2: '>=0.2 && <0.3'
  hashable: '>=1.3 && <2'
  linear: '>=1.0.1 && <2'
  msgpack: '>=1.0 && <2'
  scientific: '>=0'
  stylist-traits: '>=0.1.1 && <1'
  text: '>=0'
  vector: '>=0.13 && <1'
changelog: |
  # Revision history for fontconfig-pure

  ## 0.5 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
changelog-type: markdown
description: Resolves font descriptions to font libraries, including ones installed
  on your freedesktop (Linux or BSD system).
description-type: haddock
hash: 9c90d02566c5a9c5837d2cf9e5df9cbb530fcfa88b37787566b7e05d571c6429
homepage: https://www.freedesktop.org/wiki/Software/fontconfig/
latest: 0.5.0.0
license-name: MIT
maintainer: alcinnz@argonaut-constellation.org
synopsis: Resolves font descriptions to font libraries, including ones installed on
  your freedesktop (Linux or BSD system).
test-bench-deps:
  QuickCheck: '>=0'
  base: ^>=4.17.0.0
  containers: '>=0'
  css-syntax: '>=0'
  fontconfig-pure: '>=0'
  hspec: '>=0'
  msgpack: '>=0'
  stylist-traits: '>=0'
  text: '>=0'
