homepage: https://www.freedesktop.org/wiki/Software/fontconfig/
changelog-type: markdown
hash: b9842943d403c72b07807bcb655107d12ddd30e8b36c736b5bf8671fbd5be546
test-bench-deps:
  base: '>=4.12 && <5'
  hspec: -any
  fontconfig-pure: -any
  QuickCheck: -any
maintainer: adrian@openwork.nz
synopsis: Pure-functional language bindings to FontConfig
changelog: |
  # Revision history for fontconfig-pure

  ## 0.1.0.0 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
basic-deps:
  css-syntax: -any
  base: '>=4.12 && <5'
  text: -any
  fontconfig-pure: -any
  containers: '>=0.1 && <1'
  linear: '>=1.0.1 && <2'
  hashable: '>=1.3 && <2'
  stylist-traits: '>=0.1.1 && <1'
  scientific: -any
  freetype2: '>=0.2 && <0.3'
all-versions:
- 0.1.0.0
- 0.1.0.1
- 0.1.1.0
- 0.1.1.1
- 0.2.0.0
- 0.2.0.1
author: Adrian Cochrane
latest: 0.2.0.1
description-type: haddock
description: Resolves font descriptions to font libraries, including ones installed
  on your freedesktop (Linux or BSD system).
license-name: MIT
