all-versions:
- 0.1.0.0
- 0.1.0.1
- 0.1.1.0
- 0.1.1.1
- 0.2.0.0
- 0.2.0.1
- 0.3.0.0
- 0.3.0.1
- 0.4.0.0
- 0.5.0.0
- 0.5.0.1
author: Adrian Cochrane
basic-deps:
  QuickCheck: '>=0'
  base: '>=4.17.0.0 && <4.18'
  bytestring: '>=0'
  containers: '>=0.1 && <1'
  css-syntax: '>=0'
  fontconfig-pure: '>=0'
  freetype2: '>=0.2 && <0.3'
  hashable: '>=1.3 && <2'
  linear: '>=1.0.1 && <2'
  msgpack: '>=1.0 && <2'
  scientific: '>=0'
  stylist-traits: '>=0.1.1 && <1'
  text: '>=0'
  vector: '>=0.13 && <1'
changelog: |
  # Revision history for fontconfig-pure

  ## 0.5.0.1 -- 2025-01-17

  * Added a README file
  * Improved metadata, notably instructions on how to contribute.
  * Include missing C headerfiles.

  Apologies for having overlooked these previously!

  ## 0.5 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
changelog-type: markdown
description: |
  # FontConfig-Pure
  [Repository](https://git.argonaut-constellation.org/~alcinnz/fontconfig-pure) | [Issue Tracker](https://todo.argonaut-constellation.org/fontconfig-pure) | [Hackage](https://hackage.haskell.org/package/fontconfig-pure)

  Pure-functional language bindings to [FontConfig](https://www.freedesktop.org/wiki/Software/fontconfig/), which queries & configures your freedesktop's system font database on Linux/BSD/etc.

  That is given a font family & style it'll tell which user-installed font to use!

  Adds compatibility with [Haskell Stylist](https://hackage.haskell.org/package/stylist), so you can use CSS syntax.

  ## Contributing
  Please send patches to our [issue tracker](https://todo.argonaut-constellation.org/~alcinnz/fontconfig-pure) by either:

  * Attaching the output of `git format-patch`.
  * [git send-email](https://git-send-email.io/) to ~alcinnz/fontconfig-pure@todo.argonaut-constellation.org .
  * Linking to your fork elsewhere.

  Whichever you find most convenient.

  If you'd prefer to not make your email address public please contact alcinnz@argonaut-constellation.org !
description-type: markdown
hash: b240e6f3de30ed141664a33369e229f723af91a0a1ab8581c67a15a7bb95f727
homepage: https://www.freedesktop.org/wiki/Software/fontconfig/
latest: 0.5.0.1
license-name: MIT
maintainer: ~alcinnz/fontconfig-pure@todo.argonaut-constellation.org
synopsis: Resolves font descriptions to font libraries, including ones installed on
  your freedesktop (Linux or BSD system).
test-bench-deps:
  QuickCheck: '>=0'
  base: ^>=4.17.0.0
  containers: '>=0'
  css-syntax: '>=0'
  fontconfig-pure: '>=0'
  hspec: '>=0'
  msgpack: '>=0'
  stylist-traits: '>=0'
  text: '>=0'
