homepage: https://github.com/brendanhay/amazonka
changelog-type: ''
hash: 4b924ce8e6403f4a7954f10e17f14ddf58e3c7b032fade3234c095e0803f1892
test-bench-deps:
  bytestring: -any
  case-insensitive: -any
  base: -any
  time: -any
  unordered-containers: -any
  text: -any
  amazonka-config: -any
  amazonka-test: '>=2.0 && <2.1'
  amazonka-core: '>=2.0 && <2.1'
  tasty-hunit: -any
  tasty: -any
maintainer: Brendan Hay <brendan.g.hay+amazonka@gmail.com>, Jack Kelly <jack@jackkelly.name>
synopsis: Amazon Config SDK.
changelog: ''
basic-deps:
  base: '>=4.12 && <5'
  amazonka-core: '>=2.0 && <2.1'
all-versions:
- 0.0.0
- 0.0.1
- 0.0.2
- 0.0.3
- 0.0.4
- 0.0.5
- 0.0.6
- 0.0.7
- 0.0.8
- 0.1.0
- 0.1.1
- 0.1.2
- 0.1.3
- 0.1.4
- 0.2.0
- 0.2.1
- 0.2.2
- 0.2.3
- 0.3.0
- 0.3.1
- 0.3.2
- 0.3.3
- 0.3.4
- 0.3.5
- 0.3.6
- 1.0.0
- 1.0.1
- 1.1.0
- 1.2.0
- 1.2.0.1
- 1.2.0.2
- 1.3.0
- 1.3.1
- 1.3.2
- 1.3.3
- 1.3.3.1
- 1.3.4
- 1.3.5
- 1.3.6
- 1.3.7
- 1.4.0
- 1.4.1
- 1.4.2
- 1.4.3
- 1.4.4
- 1.4.5
- 1.5.0
- 1.6.0
- 1.6.1
- '2.0'
author: Brendan Hay
latest: '2.0'
description-type: markdown
description: "# Amazon Config SDK\n\n* [Version](#version)\n* [Description](#description)\n*
  [Contribute](#contribute)\n* [Licence](#licence)\n\n\n## Version\n \n`2.0` - Derived
  from API version @2014-11-12@ of the AWS service descriptions, licensed under Apache
  2.0.\n\n## Description\n\nDocumentation is available via [Hackage](http://hackage.haskell.org/package/amazonka-config)\nand
  the [AWS API Reference](https://aws.amazon.com/documentation/).\n\nThe types from
  this library are intended to be used with [amazonka](http://hackage.haskell.org/package/amazonka),\nwhich
  provides mechanisms for specifying AuthN/AuthZ information, sending requests,\nand
  receiving responses.\n\nLenses are used for constructing and manipulating types,\ndue
  to the depth of nesting of AWS types and transparency regarding\nde/serialisation
  into more palatable Haskell values.\nThe provided lenses should be compatible with
  any of the major lens libraries\n[lens](http://hackage.haskell.org/package/lens)
  or [lens-family-core](http://hackage.haskell.org/package/lens-family-core).\n\nSee
  [Amazonka.Config](http://hackage.haskell.org/package/amazonka-config/docs/Amazonka-Config.html)\nor
  [the AWS documentation](https://aws.amazon.com/documentation/) to get started.\n\n\n##
  Contribute\n\nFor any problems, comments, or feedback please create an issue [here
  on GitHub](https://github.com/brendanhay/amazonka/issues).\n\n> _Note:_ this library
  is an auto-generated Haskell package. Please see `amazonka-gen` for more information.\n\n\n##
  Licence\n\n`amazonka-config` is released under the [Mozilla Public License Version
  2.0](http://www.mozilla.org/MPL/).\n\nParts of the code are derived from AWS service
  descriptions, licensed under Apache 2.0.\nSource files subject to this contain an
  additional licensing clause in their header.\n"
license-name: MPL-2.0
