all-versions:
- 0.0.0
- 0.0.1
author: Kazu Yamamoto
basic-deps:
  base: '>=4.9 && <5'
  base16-bytestring: '>=0'
  base64-bytestring: '>=0'
  bytestring: '>=0'
  ech-config: '>=0'
  filepath: '>=0'
  hpke: '>=0'
  network-byte-order: '>=0'
changelog: |
  # ChangeLog for ech-config

  ## 0.0.1

  * Making Show more friendly to dnsext-*

  ## 0.0.0

  * Initial release.
changelog-type: markdown
description: Config types for TLS Encrypted Client Hello to glue DNS and TLS
description-type: haddock
hash: e64020ffdbaaf8734574dd8b20b8b0d4c367546db4ac2f50b4ad74f1a6447ba5
homepage: ''
latest: 0.0.1
license-name: BSD-3-Clause
maintainer: kazu@iij.ad.jp
synopsis: Config for TLS Encrypted Client Hello
test-bench-deps: {}
