all-versions:
- 0.0.0
author: Kazu Yamamoto
basic-deps:
  base: '>=4.9 && <5'
  base16-bytestring: '>=0'
  base64-bytestring: '>=0'
  bytestring: '>=0'
  ech-config: '>=0'
  filepath: '>=0'
  hpke: '>=0'
  network-byte-order: '>=0'
changelog: |
  # ChangeLog for ech-config

  ## 0.0.0

  * Initial release.
changelog-type: markdown
description: Config types for TLS Encrypted Client Hello to glue DNS and TLS
description-type: haddock
hash: 6ad451f18d6a4d886546024172d6ac8e309938b92571f2a09e4f94efdb7e92b6
homepage: ''
latest: 0.0.0
license-name: BSD-3-Clause
maintainer: kazu@iij.ad.jp
synopsis: Config for TLS Encrypted Client Hello
test-bench-deps: {}
