all-versions:
- 0.1.0.1
- 1.0.0.0
author: Rick Owens
basic-deps:
  base: '>=4 && <5'
  unix: '>=0'
  yaml: '>=0'
changelog: ''
changelog-type: ''
description: |-
  Turns out, all of our executables shared the same sort of
  pattern for extracting configuration out of the
  environment: find a YAML config file based on the command
  line arguments and parse that file into a haskell value using
  the yaml package. This package makes that process super
  trivial.
description-type: haddock
hash: f161d10acf7c37e68607efd11947c8ee2abd5dfeb5945aa13c86a699cf990227
homepage: ''
latest: 1.0.0.0
license-name: Apache-2.0
maintainer: rick@owenssoftware.com
synopsis: A pattern for configuring programs.
test-bench-deps: {}
