all-versions:
- 0.0.0.1
- 0.0.0.2
- 0.1.0.0
- 0.2.0.0
- 0.3.0.0
- 0.3.0.1
author: Joris Guyonvarch
basic-deps:
  base: <5
  filepath: '>=0'
  parsec: '>=0'
  text: '>=0'
  time: '>=0'
  unordered-containers: '>=0'
changelog: ''
changelog-type: ''
description: |-
  A configuration management library which supports:

  * name-value bindings,

  * required or optional imports,

  * comments.

  For details of the configuration file format, see
  <http://hackage.haskell.org/packages/archive/config-manager/latest/doc/html/Data-ConfigManager.html>.
description-type: haddock
hash: 2a7332247885a4aab19823ebe4ab9c808067901b86d5b6da0810fcf97475299b
homepage: https://gitlab.com/guyonvarch/config-manager
latest: 0.3.0.1
license-name: GPL-3.0-only
maintainer: joris@guyonvarch.me
synopsis: Configuration management
test-bench-deps:
  HUnit: '>=0'
  base: '>=0'
  config-manager: '>=0'
  directory: '>=0'
  temporary: '>=0'
  test-framework: '>=0'
  test-framework-hunit: '>=0'
  text: '>=0'
  time: '>=0'
  unordered-containers: '>=0'
