all-versions:
- 1.0.0
- 1.0.3
- 1.0.4
- 1.0.5
- 1.0.6
- 1.1.0
- 1.1.1
- 1.1.2
- 1.1.3
- 1.1.4
author: John Goerzen
basic-deps:
  MissingH: '>=1.0.0'
  base: <5
  containers: '>=0'
  mtl: <2.3
  parsec: '>=0'
changelog: ''
changelog-type: ''
description: |+
  Welcome to ConfigFile.

  For more information, visit http://software.complete.org/configfile

description-type: text
hash: 4cb481f88bbbbba5a61d2c1aa76fda01ae3d8ba9d11439a6cf56a86bfa791883
homepage: http://software.complete.org/configfile
latest: 1.1.4
license-name: BSD-3-Clause
maintainer: John Goerzen <jgoerzen@complete.org>
synopsis: Configuration file reading & writing
test-bench-deps: {}
