homepage: http://software.complete.org/configfile
changelog-type: ''
hash: 4cb481f88bbbbba5a61d2c1aa76fda01ae3d8ba9d11439a6cf56a86bfa791883
test-bench-deps: {}
maintainer: John Goerzen <jgoerzen@complete.org>
synopsis: Configuration file reading & writing
changelog: ''
basic-deps:
  MissingH: '>=1.0.0'
  base: <5
  parsec: -any
  containers: -any
  mtl: <2.3
all-versions:
- 1.0.0
- 1.0.3
- 1.0.4
- 1.0.5
- 1.0.6
- 1.1.0
- 1.1.1
- 1.1.2
- 1.1.3
- 1.1.4
author: John Goerzen
latest: 1.1.4
description-type: text
description: |+
  Welcome to ConfigFile.

  For more information, visit http://software.complete.org/configfile

license-name: BSD-3-Clause
