all-versions:
- 0.0.0
- 0.0.1
author: Timothy Hobbs
basic-deps:
  base: <5
  directory: '>=0'
  filepath: '>=0'
  unix: '>=0'
  vty-menu: '>=0'
changelog: ''
changelog-type: ''
description: Manage multiple configuration profiles for the same program.  Swap out
  dot files quickly.
description-type: haddock
hash: 78b84d7a4fcd58b06960277dfd89fc3e04f5b6bee815fde3b4bf00337182eb78
homepage: ''
latest: 0.0.1
license-name: GPL-3.0-only
maintainer: Timothy Hobbs <timothyhobbs@seznam.cz>
synopsis: A small program for swapping out dot files.
test-bench-deps: {}
