all-versions:
- 0.1.0.0
- 0.1.0.1
author: Justin Le
basic-deps:
  base: '>=4.8 && <5'
  base-compat: '>=0'
  configurator: '>=0'
  pretty: '>=0'
  semigroups: '>=0.17'
  text: '>=0'
  unordered-containers: '>=0'
changelog: |
  Changelog
  =========

  v0.1.0.1
  --------

  <https://github.com/mstksg/configurator-export/releases/tag/v0.1.0.1>

  *   Added support for backwards compatibility up to GHC 7.6

  v0.1.0.0
  --------

  <https://github.com/mstksg/configurator-export/releases/tag/v0.1.0.0>

  *   Initial release!
changelog-type: markdown
description: |+
  configurator-export
  ===================

  [![configurator-export on Stackage LTS 4](http://stackage.org/package/configurator-export/badge/lts-4)](http://stackage.org/lts-4/package/configurator-export)
  [![configurator-export on Stackage LTS](http://stackage.org/package/configurator-export/badge/lts)](http://stackage.org/lts/package/configurator-export)
  [![configurator-export on Stackage Nightly](http://stackage.org/package/configurator-export/badge/nightly)](http://stackage.org/nightly/package/configurator-export)

  [![Build Status](https://travis-ci.org/mstksg/configurator-export.svg?branch=master)](https://travis-ci.org/mstksg/configurator-export)

  Pretty printers and exporters for 'Config's from the great
  *[configurator](http://hackage.haskell.org/package/configurator)* library.

  All results are intended to be valid parsing files in the configuration file
  syntax of the library.

  For a full round trip:

  ~~~haskell
  main = do
    cfg <- load [Required "config.cfg"]
    writeConf "config.cfg" cfg
  ~~~

  This should load the config file, parse it, and then re-export it, rewriting
  the original config file.  The result should be an identical configuration
  file (with keys potentially re-arranged and re-sorted, comments removed, etc.)

  Can also export/print any `HashMap Name Value`, in the form exported from a
  `Config` using `getMap`.  Modify a map yourself to dynically
  generate/customize configuration files!

  Sample output:

  ~~~haskell
  foo {
      bar {
          baz1  = true
          baz2  = [1, 0.6, "hello", true]
      }
      aardvark  = "banana"
      monkey    = [true, false, 1.9e-3]
      zebra     = 24
  }

  foo2 {
      bar = 8.1e-8
  }

  apple   = ["cake", true]
  orange  = 8943
  ~~~

  Further configuration on sorting of keys, displaying of bools and floats, etc.
  is possible by passing in custom `ConfStyle` style option values.


description-type: markdown
hash: d97be5e02b891d7a8b9ebf2fa2694ad23c8dc59119baa50eb2eea088aa75e093
homepage: http://github.com/mstksg/configurator-export
latest: 0.1.0.1
license-name: BSD-3-Clause
maintainer: justin@jle.im
synopsis: |-
  Pretty printer and exporter for configurations from
  the "configurator" library.
test-bench-deps:
  base: '>=0'
  configurator-export: '>=0'
