all-versions:
- 0.0.1
- 0.0.2
- 0.0.3
author: Iphigenia Df <iphydf@gmail.com>
basic-deps:
  ansi-wl-pprint: '>=0'
  base: <5
  casing: '>=0'
  data-fix: '>=0'
  split: '>=0'
  transformers-compat: '>=0'
changelog: ''
changelog-type: ''
description: A Haskell implementation of encoding-independent schemas.
description-type: haddock
hash: 7806b0b6cce5e0f122dc652be57e8db6c6e97281801fb9abe9d53b083e0c04fd
homepage: https://toktok.github.io/
latest: 0.0.3
license-name: GPL-3.0-only
maintainer: Iphigenia Df <iphydf@gmail.com>
synopsis: Encoding-independent schemas for Haskell data types.
test-bench-deps:
  QuickCheck: '>=0'
  base: <5
  bytestring: '>=0'
  groom: '>=0'
  hspec: '>=0'
  schema: '>=0'
