homepage: https://toktok.github.io/
changelog-type: ''
hash: 7806b0b6cce5e0f122dc652be57e8db6c6e97281801fb9abe9d53b083e0c04fd
test-bench-deps:
  bytestring: -any
  base: <5
  hspec: -any
  groom: -any
  schema: -any
  QuickCheck: -any
maintainer: Iphigenia Df <iphydf@gmail.com>
synopsis: Encoding-independent schemas for Haskell data types.
changelog: ''
basic-deps:
  ansi-wl-pprint: -any
  data-fix: -any
  split: -any
  base: <5
  casing: -any
  transformers-compat: -any
all-versions:
- 0.0.1
- 0.0.2
- 0.0.3
author: Iphigenia Df <iphydf@gmail.com>
latest: 0.0.3
description-type: haddock
description: A Haskell implementation of encoding-independent schemas.
license-name: GPL-3.0-only
