all-versions:
- 1.0.0
- 1.1.0
- 1.1.1.0
- 1.2.0
- 1.2.1
- 1.2.2
- 1.2.2.1
author: YusukeNomura
basic-deps:
  base: '>=4 && <5'
  bytestring: '>=0'
  data-default: '>=0'
  network-uri: '>=2.6'
  parsec: '>=0'
  template-haskell: '>=0'
  transformers: '>=0'
changelog: ''
changelog-type: ''
description: Simple config file parser generator
description-type: haddock
hash: f191b12a5aa3d8caa4e60d573376fb3c5645fc81e062baac6b58cfa155c5eae6
homepage: https://github.com/yunomu/simple-config
latest: 1.2.2.1
license-name: BSD-3-Clause
maintainer: yunomu@gmail.com
synopsis: Simple config file parser generator
test-bench-deps:
  base: '>=4 && <5'
  hspec: '>=0'
