all-versions:
- 0.1.0.0
- 0.1.0.2
- 0.1.0.3
author: Martin Allen, Ben Weitzman
basic-deps:
  aeson: '>=0.7 && <1.3'
  base: '>=4.7 && <5'
  insert-ordered-containers: '>=0'
  lens: '>=0'
  servant: '>=0.10 && <0.12'
  servant-swagger: '>=1.1.2.1'
  servant-zeppelin: '>=0.1 && <0.2'
  singletons: '>=2.2 && <2.3'
  swagger2: '>=2.1 && <2.2'
  text: '>=1.2 && <1.3'
changelog: ''
changelog-type: ''
description: |
  # servant-side-loaded
description-type: markdown
hash: 1ebc4e4c2a3b2059215a414a66b98f4b8454fd4b622b00fbd338c34ef909f7ba
homepage: https://github.com/martyall/servant-zeppelin#readme
latest: 0.1.0.3
license-name: BSD-3-Clause
maintainer: martin[dot]allen26[at]gmail.com
synopsis: Swagger instances for servant-zeppelin combinators.
test-bench-deps:
  aeson: '>=0'
  base: '>=0'
  containers: '>=0'
  hspec: '>=0'
  insert-ordered-containers: '>=0'
  lens: '>=0'
  servant: '>=0'
  servant-swagger: '>=0'
  servant-zeppelin: '>=0'
  servant-zeppelin-swagger: '>=0'
  swagger2: '>=0'
