all-versions:
- 0.2.0
author: Sean Hess
basic-deps:
  aeson: '>=0'
  base: '>=4.7 && <5'
  binary: '>=0'
  bytestring: '>=0'
  containers: '>=0'
  http-types: '>=0'
  monad-logger: '>=0'
  text: '>=0'
  wai: '>=0'
changelog: ''
changelog-type: ''
description: |
  # services
description-type: markdown
hash: 695e61878895ffd38b9f75886317aa8dd3d725f786f719bf5866a27a0be5cdf1
homepage: https://github.com/seanhess/services#readme
latest: 0.2.0
license-name: BSD-3-Clause
maintainer: seanhess@gmail.com
synopsis: Tools for building services
test-bench-deps:
  base: '>=0'
  services: '>=0'
  tasty: '>=0'
  tasty-hunit: '>=0'
