homepage: ''
changelog-type: ''
hash: fc1717995d3b2f35a0be0d486cae777754d703f95a6aedb395fd1f1dd8cade99
test-bench-deps: {}
maintainer: Danila Danko <https://github.com/deemp>
synopsis: Instances of classes from [openapi3](https://hackage.haskell.org/package/openapi3)
  for [servant-queryparam-server](https://hackage.haskell.org/package/servant-queryparam-server).
changelog: ''
basic-deps:
  warp: -any
  bytestring: -any
  base: '>=4.16 && <5'
  text: -any
  servant-openapi3: -any
  servant-server: '>=0.19'
  servant: '>=0.19'
  openapi3: -any
  servant-queryparam-core: '>=1.0.0'
all-versions:
- 1.0.0
author: Kristof Bastiaensen
latest: 1.0.0
description-type: haddock
description: ''
license-name: BSD-3-Clause
