homepage: ''
changelog-type: ''
hash: 15e11066df781da669e510ebdb89b7e3df344020561b2ea3715a05fdfb0c54a8
test-bench-deps: {}
maintainer: Danila Danko <https://github.com/deemp>
synopsis: Instances of classes from openapi3 for servant-queryparam-core.
changelog: ''
basic-deps:
  base: '>=4.16 && <5'
  servant-openapi3: -any
  servant: '>=0.19'
  openapi3: -any
  servant-queryparam-core: '>=2.0.0'
all-versions:
- 1.0.0
- 1.0.1
- 1.0.2
- 2.0.0
author: Kristof Bastiaensen
latest: 2.0.0
description-type: haddock
description: Instances of classes from [openapi3](https://hackage.haskell.org/package/openapi3)
  for [servant-queryparam-core](https://hackage.haskell.org/package/servant-queryparam-core).
license-name: BSD-3-Clause
