all-versions:
- 1.0.0
- 1.1.0
- 1.2.0
author: Andrii Demydenko <worm2fed@gmail.com>, Anchor Engineering <engineering@lists.anchor.net.au>,
  Servant Contributors
basic-deps:
  base: '>=4.10 && <4.18'
  clock: '>=0.8.3 && <0.9'
  ghc-prim: '>=0.8.0 && <0.10'
  hashable: '>=1.4.2 && <1.5'
  http-types: '>=0.12.3 && <0.13'
  prometheus-client: '>=1.1.0 && <1.2'
  servant: '>=0.14 && <0.20'
  text: '>=1.2.5 && <2.1'
  wai: '>=3.2.3 && <3.3'
changelog: |
  Unreleased
  ==========


  1.2.0
  =======

  - Add an `HasEndpoint` instance for `AuthProtect`

  1.1.0
  =======

  - Support GHC 9.4

  1.0.0
  =======

  Initial release.
changelog-type: markdown
description: |
  # servant-prometheus

  [![Build status](https://github.com/worm2fed/servant-prometheus/actions/workflows/ci.yml/badge.svg)](https://github.com/worm2fed/servant-prometheus/actions/workflows/ci.yml)
  [![Hackage](https://img.shields.io/hackage/v/servant-prometheus.svg?logo=haskell)](https://hackage.haskell.org/package/servant-prometheus)

  # Servant Performance Counters

  This package lets you track performance counters for each of your Servant endpoints using [Prometheus](https://prometheus.io/).

  # Usage

  `servant-prometheus` knows how to handle all official Servant combinators out of the box.

  ## Instrumenting your API

  To use `servant-prometheus`, you'll need to wrap your WAI application with the provided middleware.

  ```haskell
  import Network.Wai.Handler.Warp
  import Prometheus.Servant

  main :: IO ()
  main = do
    let api    = ...
        server = ...
        app = prometheusMiddleware defaultMetrics api server

    run 8080 app
  ```

  ## Custom metrics

  Note, that in example above `defaultMetrics` used, which actually provided as an example and good starting point.
  If you want to use your custom metrics (eg you want another labels), you'll need to define an implementation for `Metrics mLatencyLabel mActiveLabel` data.
  That's not hard, just copy-paste and tweak accordingly to your needs.

  ## Runtime overhead

  Instrumenting your API introduces a non-zero runtime overhead, on the order of 200 - 600 µsec depending upon your machine. It's a good idea to run the benchmarks on your intended production platform to get an idea of how large the overhead will be. You'll need to have `wrk` installed to run the benchmarks.

  In general, the runtime overhead should be effectively negligible if your handlers are issuing network requests, such as to databases. If you have handlers that are small, CPU-only, and requested frequently, you will see a performance hit from `servant-prometheus`.
description-type: markdown
hash: 2e55c556dd628276652dd5e7efaae9c76cec91a30b230291104388ddaa1664a0
homepage: https://github.com/worm2fed/servant-prometheus#readme
latest: 1.2.0
license-name: BSD-3-Clause
maintainer: Andrii Demydenko <worm2fed@gmail.com>
synopsis: Helpers for using prometheus with servant
test-bench-deps:
  aeson: '>=2.0 && <2.2'
  base: '>=4.10 && <4.18'
  containers: '>=0.6.5 && <0.7'
  hspec: '>=2 && <3'
  hspec-expectations-pretty-diff: '>=0.7.2.2 && <0.8'
  http-client: '>=0.7.13 && <0.8'
  process: '>=1.6.16 && <1.7'
  prometheus-client: '>=0'
  servant: '>=0'
  servant-client: '>=0.14 && <0.20'
  servant-prometheus: '>=0'
  servant-server: '>=0.14 && <0.20'
  text: '>=0'
  wai: '>=0'
  warp: '>=3.2.4 && <3.4'
