homepage: ''
changelog-type: ''
hash: 59614baf6215e0973497d79901d34e1c0f0407d1110e56e4ccd74781662a8944
test-bench-deps: {}
maintainer: Danila Danko <https://github.com/deemp>
synopsis: Instances of classes from openapi3 for servant-queryparam-core.
changelog: ''
basic-deps:
  base: '>=4.16 && <5'
  servant-openapi3: -any
  servant: '>=0.19'
  openapi3: -any
  servant-queryparam-core: '>=1.0.0'
all-versions:
- 1.0.0
- 1.0.1
author: Kristof Bastiaensen
latest: 1.0.1
description-type: haddock
description: Instances of classes from [openapi3](https://hackage.haskell.org/package/openapi3)
  for [servant-queryparam-core](https://hackage.haskell.org/package/servant-queryparam-core).
license-name: BSD-3-Clause
