all-versions:
- 0.1.0.0
- 0.1.0.1
author: Daishi Nakajima
basic-deps:
  base: '>=4.7 && <5'
  insert-ordered-containers: '>=0'
  lens: '>=0'
  servant: '>=0'
  servant-mock: '>=0'
  servant-server: '>=0'
  servant-swagger: '>=0'
  swagger2: '>=0'
  text: '>=0'
changelog: ''
changelog-type: ''
description: |
  # servant-swagger-tags
description-type: markdown
hash: 2d743e9ad1cfcca537acc99e0b97e0e4feda3b5c842937dbf5895261e3105bf1
homepage: https://github.com/nakaji-dayo/servant-swagger-tags#readme
latest: 0.1.0.1
license-name: BSD-3-Clause
maintainer: nakaji.dayo@mail.com
synopsis: Swagger Tags for Servant
test-bench-deps: {}
