all-versions:
- 0.0.0.0
author: Cary Robbins
basic-deps:
  aeson: '>=0'
  aeson-pretty: '>=0'
  base: '>=4.7 && <5'
  bytestring: '>=0'
  directory: '>=0'
  text: '>=0'
changelog: ''
changelog-type: ''
description: |
  # karabiner-config
description-type: markdown
hash: df1a0ee2213b748254c829624d48cb560bdcf6f7d86586177835b5b311574ad9
homepage: https://github.com/carymrobbins/karabiner-config#readme
latest: 0.0.0.0
license-name: BSD-3-Clause
maintainer: carymrobbins@gmail.com
synopsis: Karabiner elements configuration generation
test-bench-deps:
  aeson: '>=0'
  aeson-pretty: '>=0'
  base: '>=4.7 && <5'
  bytestring: '>=0'
  directory: '>=0'
  file-embed: '>=0'
  hspec: '>=0'
  karabiner-config: '>=0'
  process: '>=0'
  temporary: '>=0'
  text: '>=0'
