homepage: https://github.com/carymrobbins/karabiner-config#readme
changelog-type: ''
hash: df1a0ee2213b748254c829624d48cb560bdcf6f7d86586177835b5b311574ad9
test-bench-deps:
  bytestring: -any
  base: '>=4.7 && <5'
  aeson-pretty: -any
  hspec: -any
  text: -any
  process: -any
  karabiner-config: -any
  file-embed: -any
  temporary: -any
  aeson: -any
  directory: -any
maintainer: carymrobbins@gmail.com
synopsis: Karabiner elements configuration generation
changelog: ''
basic-deps:
  bytestring: -any
  base: '>=4.7 && <5'
  aeson-pretty: -any
  text: -any
  aeson: -any
  directory: -any
all-versions:
- 0.0.0.0
author: Cary Robbins
latest: 0.0.0.0
description-type: markdown
description: |
  # karabiner-config
license-name: BSD-3-Clause
