all-versions:
- 0.1.0.0
- 0.1.0.1
- 0.1.0.2
- 0.1.0.3
- 0.1.0.4
author: Alfredo Di Napoli
basic-deps:
  base: '>=4.7 && <5'
  containers: <0.7.0.0
  ekg-core: <0.2.0.0
  microlens-th: <0.5.0.0
  prometheus: '>=0.4.0 && <3.0.0'
  text: <1.3.0.0
  transformers: <0.6.0.0
  unordered-containers: <0.3.0.0
changelog: ''
changelog-type: ''
description: Please see README.md
description-type: haddock
hash: d95487be7f282976cfb23c5b3826eaa1a279aff1e3821b29cf60ad3164e903ab
homepage: https://github.com/adinapoli/ekg-prometheus-adapter#readme
latest: 0.1.0.4
license-name: MIT
maintainer: alfredo.dinapoli@gmail.com
synopsis: Easily expose your EKG metrics to Prometheus
test-bench-deps:
  base: '>=0'
  ekg-prometheus-adapter: '>=0'
