all-versions:
- 0.1.0.0
- 0.1.0.1
- 0.1.0.2
- 0.1.0.3
- 0.1.0.4
- 0.1.0.5
author: Alfredo Di Napoli
basic-deps:
  base: '>=4.7 && <5'
  containers: '>=0.6.7 && <0.8'
  ekg-core: '>=0.1.1 && <0.2'
  microlens-th: '>=0.4.3 && <0.5'
  prometheus: '>=0.4.0 && <3.0.0'
  text: '>=2.0.2 && <2.2'
  transformers: '>=0.5.6 && <0.7'
  unordered-containers: '>=0.2.20 && <0.3'
changelog: ''
changelog-type: ''
description: Please see README.md
description-type: haddock
hash: 1ec198c99bdf0b4d322eb64fc8840056c53433fa844cdd2c335406b5dc157786
homepage: https://github.com/adinapoli/ekg-prometheus-adapter#readme
latest: 0.1.0.5
license-name: MIT
maintainer: alfredo.dinapoli@gmail.com
synopsis: Easily expose your EKG metrics to Prometheus
test-bench-deps:
  base: '>=0'
  ekg-prometheus-adapter: '>=0'
