all-versions:
- 0.3.0.0
- 0.4.0.0
- 0.5.0.0
author: Alexander Thiemann <mail@athiemann.net>
basic-deps:
  base: '>=4.8 && <5'
  highjson: '>=0.4'
  hvect: '>=0.4'
  insert-ordered-containers: '>=0.2'
  lens: '>=0'
  swagger2: '>=2.1.3'
  text: '>=0'
changelog: ''
changelog-type: ''
description: Derive swagger instances from highjson specs
description-type: haddock
hash: 0624c1117cd5b36bea36c802bac1f84fd9fbe62d5585d504011a7bb2a5ae2011
homepage: https://github.com/agrafix/highjson
latest: 0.5.0.0
license-name: MIT
maintainer: Alexander Thiemann <mail@athiemann.net>
synopsis: Derive swagger instances from highjson specs
test-bench-deps:
  QuickCheck: '>=2.8'
  aeson: '>=0'
  base: '>=0'
  bytestring: '>=0'
  highjson: '>=0'
  highjson-swagger: '>=0'
  hspec: '>=2.0'
  lens: '>=0'
  swagger2: '>=0'
  text: '>=0'
