homepage: https://github.com/agrafix/highjson
changelog-type: ''
hash: 0624c1117cd5b36bea36c802bac1f84fd9fbe62d5585d504011a7bb2a5ae2011
test-bench-deps:
  bytestring: -any
  base: -any
  hspec: '>=2.0'
  text: -any
  lens: -any
  swagger2: -any
  QuickCheck: '>=2.8'
  highjson: -any
  aeson: -any
  highjson-swagger: -any
maintainer: Alexander Thiemann <mail@athiemann.net>
synopsis: Derive swagger instances from highjson specs
changelog: ''
basic-deps:
  insert-ordered-containers: '>=0.2'
  base: '>=4.8 && <5'
  text: -any
  hvect: '>=0.4'
  lens: -any
  swagger2: '>=2.1.3'
  highjson: '>=0.4'
all-versions:
- 0.3.0.0
- 0.4.0.0
- 0.5.0.0
author: Alexander Thiemann <mail@athiemann.net>
latest: 0.5.0.0
description-type: haddock
description: Derive swagger instances from highjson specs
license-name: MIT
