all-versions:
- 0.0.0.0
- 0.0.0.1
author: Mike Solomon
basic-deps:
  aeson: '>=1.4.7 && <1.5'
  base: '>=4.7 && <5'
  text: '>=1.2.4 && <1.3'
  unordered-containers: '>=0.2.10 && <0.3'
  vector: '>=0.12.1 && <0.13'
changelog: |
  # Changelog for openapi-typed

  ## 0.0.0.1

  Patch to initial release.

  ## 0.0.0.0

  Initial release.

  ## Unreleased changes
changelog-type: markdown
description: |-
  # openapi-typed

  Haskell types for OpenAPI 3.0.0. The types follow the following opinonated conventions and deviations from the standards:

  - For each OpenAPI object represented as `data`, provides the following:
    - a docstring showing how the constructor works
    - a constructor with fields named using the convention `_<data>_field`
    - a derivation of `Eq` for each data class
    - a derivation of `Show` for each data class
    - a derivation of `ToJSON` for each data class
    - a derivation of `FromJSON` for each data class
    - a getter for each field using the convention `get<data><field>`, where the field is capitalized, ie `getPathItemSummary`
    - a setter for each field using the convention `set<data><field>`, where the field is capitalized, ie `setPathItemSummary`
    - an `either` function for all datatypes with multiple construtors that take a single argument using the convention `either<data><constructor>`, ie `eitherReferenceOrRef`
  - Adds the possibility to use `x-` extensions on almost all objects, as this happens a lot in the wild.
  - Changes the `items` type in shema to accept a tuple in addition to a schema and a reference.

  The Hackage package is in `openapi-typed`. The tests show how to use this library to parse the [Slack](https://slack.com) and [Stripe](https://stripe.com) OpenAPI specs.
description-type: markdown
hash: a13ecef8c4b1d696a2631d82aea37d78c866c0199fa56dd6cf1f1337b928b53a
homepage: https://github.com/meeshkan/openapi-haskell#readme
latest: 0.0.0.1
license-name: BSD-3-Clause
maintainer: mike@meeshkan.com
synopsis: Types for OpenAPI
test-bench-deps:
  aeson: '>=1.4.7 && <1.5'
  base: '>=4.7 && <5'
  hspec: '>=2.7.1'
  openapi-typed: '>=0'
  optics-core: '>=0.3'
  optics-extra: '>=0.3'
  text: '>=1.2.4 && <1.3'
  unordered-containers: '>=0.2.10 && <0.3'
  yaml: '>=0.11.3.0'
