all-versions:
- 0.1.0
- 0.2.0
- 0.2.1
- 0.3.0
- 0.3.1
author: Alexander Dorofeev <aka.spin@gmail.com>spin
basic-deps:
  base: '>=4 && <5'
  data-default: '>=0'
  global-variables: '>=0'
  transformers: '>=0.2'
changelog: ''
changelog-type: ''
description: |-
  @Data.Global.Config@ provides brain-free pattern to work with global
  configurations. Use wisely.
description-type: haddock
hash: 967e57ee6a69bb5382395f6cf1bc1e423efccd5bc080b80c1f84826ed305fbb7
homepage: https://github.com/akaspin/global-config
latest: 0.3.1
license-name: BSD-3-Clause
maintainer: Alexander Dorofeev <aka.spin@gmail.com>
synopsis: Global mutable configuration
test-bench-deps:
  HUnit: '>=1.2 && <2'
  QuickCheck: '>=2.4'
  base: '>=4 && <5'
  bytestring: '>=0'
  data-default: '>=0'
  global-config: '>=0'
  test-framework: '>=0.4.1'
  test-framework-hunit: '>=0'
  test-framework-quickcheck2: '>=0'
  transformers: '>=0.2'
