all-versions:
- '0.1'
- '0.2'
author: Jens Petersen <juhpetersen@gmail.com>
basic-deps:
  ansi-terminal: '>=0'
  base: <5
  bytestring: '>=0'
  extra: '>=0'
  http-conduit: '>=0'
  http-directory: '>=0.1.9'
  simple-cmd-args: '>=0.1.7'
  simple-prompt: '>=0.2'
  text: '>=0'
  time: '>=0'
changelog: |
  # Version history for fedora-composes

  ## 0.2 (2024-02-14)
  - output compose urls and use multiple lines for status
  - status: default to showing latest finished and prompt to show older
  - if STARTED only print STATUS time
  - handle missing STATUS and COMPOSE_ID
  - default to up to 10 composes
  - add --latest option
  - append logs/global to url if doomed

  ## 0.1 (2022-08-11)
  - initial release with list and status commands and filtering
changelog-type: markdown
description: "# fedora-composes\n\nA small tool to list and check the status of Fedora
  composes.\n\n## Examples\n\n`$ fedora-composes list --latest rawhide`\n```\nhttps://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20240214.n.1\n```\n`$
  fedora-composes list -l2 branched`\n```\nhttps://kojipkgs.fedoraproject.org/compose/branched/Fedora-40-20240214.n.0\nhttps://kojipkgs.fedoraproject.org/compose/branched/Fedora-40-20240213.n.1\n```\n`$
  fedora-composes status --no-more branched`\n```\nhttps://kojipkgs.fedoraproject.org/compose/branched/Fedora-40-20240214.n.0/logs/global/\n2024-02-14
  15:19:10 +08\n2024-02-14 15:31:52 +08 DOOMED\n\nhttps://kojipkgs.fedoraproject.org/compose/branched/Fedora-40-20240213.n.1\n2024-02-14
  03:40:26 +08\n2024-02-14 08:52:37 +08 FINISHED_INCOMPLETE\n\n```\n\n`$ fedora-composes
  status -n updates 39`\n```\nhttps://kojipkgs.fedoraproject.org/compose/updates/Fedora-39-updates-testing-20240214.0\n2024-02-14
  09:25:36 +08\n2024-02-14 10:03:51 +08 FINISHED\n\n```\n\n## Usage\n\n`$ fedora-composes
  --version`\n```\n0.2\n```\n`$ fedora-composes --help`\n```\ncheck status of fedora
  composes\n\nUsage: fedora-composes [--version] COMMAND\n\n  description here\n\nAvailable
  options:\n  -h,--help                Show this help text\n  --version                Show
  version\n\nAvailable commands:\n  list                     List dirs/composes (by
  default only last compose)\n  status                   Show compose status\n```\n\nThere
  is the notion of repos and composes.\n\nFor example `Fedora-39-updates` is a repo\nand
  `Fedora-39-updates-20230810.0` is a compose for it.\n\nFiltering is case insensitive.\n\n###
  list\n\n`fedora-composes list` lists releases and other subdirs (rawhide, updates,
  branched, etc)\n\n`fedora-composes list updates` shows latest updates composes\n\n`fedora-composes
  list updates fedora-36` shows latest F36 updates composes\n\n`fedora-composes list
  branched` shows latest branched composes\n\n`$ fedora-composes list --help`\n```\nUsage:
  fedora-composes list [-d|--debug] \n                            [(-a|--all-composes)
  | (-L|--latest) | \n                              (-l|--limit LIMIT)] [-r|--repos]
  [DIR] [SUBSTR]\n\n  List dirs/composes (by default only last compose)\n\nAvailable
  options:\n  -d,--debug               debug output\n  -a,--all-composes        All
  composes\n  -L,--latest              Only latest compose\n  -l,--limit LIMIT         Max
  number of composes\n  -r,--repos               Only list target repos\n  -h,--help
  \               Show this help text\n```\n\n### status\n\n`fedora-composes status
  rawhide` shows time and status of newest rawhide\n\n`fedora-composes status updates
  fedora-39` shows time and status of updates push\n\n`fedora-composes status branched
  39` shows time and status of branched compose\n\n`$ fedora-composes status --help`\n```\nUsage:
  fedora-composes status [-d|--debug] \n                              [(-a|--all-composes)
  | (-L|--latest) | \n                                (-l|--limit LIMIT)] [-n|--no-more]
  DIR [SUBSTR]\n\n  Show compose status\n\nAvailable options:\n  -d,--debug               debug
  output\n  -a,--all-composes        All composes\n  -L,--latest              Only
  latest compose\n  -l,--limit LIMIT         Max number of composes\n  -n,--no-more
  \            Do not prompt for more results\n  -h,--help                Show this
  help text\n```\n\n## Installation\nfedora-composes rpm builds are available from
  Copr:\n<https://copr.fedorainfracloud.org/coprs/petersen/fedora-composes/>\n\n##
  Build from source\nstack/cabal/cabal-rpm install\n"
description-type: markdown
hash: c7e619060aecf15c9202b7de83e420ae033235d9a2573e058e464c73a76f4db2
homepage: https://github.com/juhp/fedora-composes
latest: '0.2'
license-name: BSD-3-Clause
maintainer: Jens Petersen <juhpetersen@gmail.com>
synopsis: Query Fedora composes
test-bench-deps:
  base: '>=4 && <5'
  simple-cmd: '>=0'
