all-versions:
- '0.1'
- '0.2'
- 0.2.1
author: Jens Petersen <juhpetersen@gmail.com>
basic-deps:
  ansi-terminal: '>=0'
  base: <5
  bytestring: '>=0'
  extra: '>=0'
  http-conduit: '>=0'
  http-directory: '>=0.1.9'
  simple-cmd-args: '>=0.1.7'
  simple-prompt: '>=0.2'
  text: '>=0'
  time: '>=0'
changelog: |
  # Version history for fedora-composes

  ## 0.2.1 (2024-09-09)
  - status: for updates default to yes for more
  - status: don't prompt for more with --limit
  - ignore undated compose directories
  - add readme url to help description

  ## 0.2 (2024-02-14)
  - output compose urls and use multiple lines for status
  - status: default to showing latest finished and prompt to show older
  - if STARTED only print STATUS time
  - handle missing STATUS and COMPOSE_ID
  - default to up to 10 composes
  - add --latest option
  - append logs/global to url if doomed

  ## 0.1 (2022-08-11)
  - initial release with list and status commands and filtering
changelog-type: markdown
description: "# fedora-composes\n\nA small tool to list and check the status of Fedora
  composes.\n\n## Examples\n\n`$ fedora-composes list --latest rawhide`\n\n```\nhttps://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20240909.n.0\n```\n`$
  fedora-composes list -l2 branched`\n\n```\nhttps://kojipkgs.fedoraproject.org/compose/branched/Fedora-41-20240909.n.0\nhttps://kojipkgs.fedoraproject.org/compose/branched/Fedora-41-20240908.n.0\n```\n`$
  fedora-composes status --no-more branched`\n\n```\nhttps://kojipkgs.fedoraproject.org/compose/branched/Fedora-41-20240909.n.0\n2024-09-09
  15:15:03 +08\n2024-09-09 19:59:30 +08 FINISHED_INCOMPLETE\n\n```\n\n`$ fedora-composes
  status -n updates 40`\n\n```\nhttps://kojipkgs.fedoraproject.org/compose/updates/Fedora-40-updates-testing-20240909.0\n2024-09-09
  22:33:40 +08 STARTED\n\nhttps://kojipkgs.fedoraproject.org/compose/updates/Fedora-40-updates-20240909.0\n2024-09-09
  08:15:35 +08\n2024-09-09 09:13:03 +08 FINISHED\n\n```\n\n## Usage\n\n`$ fedora-composes
  --version`\n\n```\n0.2.1\n```\n`$ fedora-composes --help`\n\n```\ncheck status of
  fedora composes\n\nUsage: fedora-composes [--version] COMMAND\n\n  https://github.com/juhp/fedora-composes#readme\n\nAvailable
  options:\n  -h,--help                Show this help text\n  --version                Show
  version\n\nAvailable commands:\n  list                     List dirs/composes (by
  default only last compose)\n  status                   Show compose status\n```\n\nThere
  is the notion of repos and composes.\n\nFor example `Fedora-40-updates` is a repo\nand
  `Fedora-40-updates-20240809.0` is a compose for it.\n\nFiltering is case insensitive.\n\n###
  list\n\n`fedora-composes list` lists releases and other subdirs (rawhide, updates,
  branched, etc)\n\n`fedora-composes list updates` shows latest updates composes\n\n`fedora-composes
  list updates fedora-36` shows latest F36 updates composes\n\n`fedora-composes list
  branched` shows latest branched composes\n\n`$ fedora-composes list --help`\n\n```\nUsage:
  fedora-composes list [-d|--debug] \n                            [(-a|--all-composes)
  | (-L|--latest) | \n                              (-l|--limit LIMIT)] [-r|--repos]
  [DIR] [SUBSTR]\n\n  List dirs/composes (by default only last compose)\n\nAvailable
  options:\n  -d,--debug               debug output\n  -a,--all-composes        All
  composes\n  -L,--latest              Only latest compose\n  -l,--limit LIMIT         Max
  number of composes\n  -r,--repos               Only list target repos\n  -h,--help
  \               Show this help text\n```\n\n### status\n\n`fedora-composes status
  rawhide` shows time and status of newest rawhide\n\n`fedora-composes status updates
  fedora-40` shows time and status of updates push\n\n`fedora-composes status branched
  41` shows time and status of branched compose\n\n`$ fedora-composes status --help`\n\n```\nUsage:
  fedora-composes status [-d|--debug] \n                              [(-a|--all-composes)
  | (-L|--latest) | \n                                (-l|--limit LIMIT)] [-n|--no-more]
  DIR [SUBSTR]\n\n  Show compose status\n\nAvailable options:\n  -d,--debug               debug
  output\n  -a,--all-composes        All composes\n  -L,--latest              Only
  latest compose\n  -l,--limit LIMIT         Max number of composes\n  -n,--no-more
  \            Do not prompt for more results\n  -h,--help                Show this
  help text\n```\n\n## Installation\nfedora-composes rpm builds are available from
  Copr:\n<https://copr.fedorainfracloud.org/coprs/petersen/fedora-composes/>\n\n##
  Build from source\nstack/cabal/cabal-rpm install\n"
description-type: markdown
hash: 33c3f91fd97d8839eea5e6a86364031f14bd9a909060ed3d4aeacd691a82c9c9
homepage: https://github.com/juhp/fedora-composes
latest: 0.2.1
license-name: BSD-3-Clause
maintainer: Jens Petersen <juhpetersen@gmail.com>
synopsis: Query Fedora composes
test-bench-deps:
  base: '>=4 && <5'
  simple-cmd: '>=0'
