all-versions:
- 0.0.1
author: Anupam Jain
basic-deps:
  base: '>=4.7 && <4.9'
  blaze-builder: '>=0'
  bytestring: '>=0'
  containers: '>=0'
  filepath: '>=0'
  http-types: '>=0'
  mime-types: '>=0'
  path-pieces: '>=0'
  random: '>=0'
  snap: '>=0'
  template-haskell: '>=0'
  text: '>=0'
changelog: ''
changelog-type: ''
description: |
  Snap-Routes
  ===========

  Snap-routes provides typesafe routing for snap applications.

  Features
  ========

  Snap-routes adds the following features on top of Snap -

    - Typesafe URLs, including automatic boilerplate generation using TH. Including features such as -
      - Nested Routes
      - Subsites
      - Route Annotations
    - Seamlessly mix and match "unrouted" request handlers with typesafe routing.
    - Sitewide Master data which is passed to all handlers and can be used for persistent data (like DB connections)


  Changelog
  =========

  * 0.0.1   : Intial release
description-type: markdown
hash: 005d4eb75c09bc6ef55a45654524f5bcf898e7b0222bc87aa4b0f52956147db1
homepage: ''
latest: 0.0.1
license-name: MIT
maintainer: ajnsit@gmail.com
synopsis: Typesafe URLs for Snap applications.
test-bench-deps: {}
