all-versions:
- 0.1.0.0
author: Geoffrey Roberts <geoffrey.roberts@anchor.com.au>
basic-deps:
  base: '>=4.7 && <4.8'
  configurator: '>=0'
  text: '>=0'
  unordered-containers: '>=0'
changelog: ''
changelog-type: ''
description: Methods to manipulate Configurator objects for Snap & Snaplets
description-type: haddock
hash: 71986e8dadf211a98ccfe9ba188e1db099dc7a5d993c9f4bf273d267ddaa2a58
homepage: ''
latest: 0.1.0.0
license-name: BSD-3-Clause
maintainer: Anchor Engineering <engineering@anchor.com.au>
synopsis: Methods to manipulate Configurator objects for Snap & Snaplets
test-bench-deps: {}
