all-versions:
- 0.0.3.3
- 0.5.0
- 0.6.0
- 0.7.0
- 0.8.0
author: Ivan Perez
basic-deps:
  base: '>=4 && <5'
  keera-hails-mvc-model-protectedmodel: '>=0'
  keera-hails-mvc-view: '>=0'
  keera-hails-mvc-view-gtk: '>=0'
changelog: ''
changelog-type: ''
description: |-
  Keera Hails is a rapid application development system.

  The idea behind Hails is that you should be able to build cross platform
  applications with minimal effort, very quickly, and the result should be easy
  to maintain.

  This package defines an environment that combines a model and a view, where
  the latter is implemented using GTK+. Users of this package can install
  additional conditions that keep both in sync using keera-hails-reactivevalues
  to define such conditions.
description-type: haddock
hash: a18893811e156fcd9a92767f91ebd97f62ce377503951c5b790b24c835d18f9c
homepage: http://www.keera.co.uk/blog/community/
latest: 0.8.0
license-name: BSD-3-Clause
maintainer: support@keera.co.uk
synopsis: Haskell on Gtk rails - Gtk-based global environment for MVC applications
test-bench-deps: {}
