all-versions:
- 0.0.3.3
- 0.8.0
author: Ivan Perez
basic-deps:
  MissingK: '>=0'
  base: '>=4 && <5'
  directory: '>=0'
  filepath: '>=0'
changelog: ''
changelog-type: ''
description: |-
  Keera Hails is a rapid application development system.

  The idea behind Hails is that you should be able to build cross platform
  applications with minimal effort, very quickly, and the result should be easy
  to maintain.

  Large Hails applications are structured following an optimized MVC
  architecture. Values are updated either from the view to the model, or from
  the model to the view. Internally, rules use a notion of direction in the
  update to determine how different components must be updated.

  This library provides a simple, defaut way of storing configuration settings
  for an application.
description-type: haddock
hash: 4f89739c65cb3ecb153678e0ad107c8c023f8b2a22e63ea58cdbbdfd586bfb5c
homepage: http://www.keera.co.uk/blog/community/
latest: 0.8.0
license-name: BSD-3-Clause
maintainer: support@keera.co.uk
synopsis: Haskell on Gtk rails - Easy handling of configuration files
test-bench-deps: {}
