all-versions:
- 0.1.0.0
- 0.1.0.1
author: Anton Kholomiov
basic-deps:
  aeson: '>=0'
  aeson-pretty: '>=0'
  base: '>=4.7 && <5'
  blaze-html: '>=0'
  blaze-markup: '>=0'
  bytestring: '>=0'
  data-default: '>=0'
  file-embed-lzma: '>=0'
  http-api-data: '>=0'
  lens: '>=0'
  mig: '>=0.2.0.1'
  openapi3: '>=0'
  text: '>=0'
changelog: ''
changelog-type: ''
description: "# mig-swagger-ui\n\nThe package defines utils to add swagger UI for
  mig library.\nTo add swagger just use function `withSwagger`:\n\n```haskell\nmain
  = runServer port (withSwagger def server)\n```\n\nWith `SwaggerConfig` we can update
  defaults.\nTo set information on app we can use `mapSchema` field of the swagger
  config.\n\nThere is type `DefaultInfo` to set common fields:\n\n```haskell\nmain
  = runServer port (withSwagger swaggerConfig server)\n  where\n    swaggerConfig
  =\n      def\n        { swaggerFile = \"swagger.json\"\n        , staticDir = \"swagger-ui\"\n
  \       , mapSchema = pure . addDefaultInfo info\n        }\n\n    info =\n      DefaultInfo\n
  \       { title = \"Hello world app\"\n        , description = \"Demo application\"\n
  \       , version = \"1.0\"\n        }\n```\n\nAlso see package `openapi3` on how
  to update OpenApi schema.\n\n## Aknowledgments \n\nThanks to Oleg Grenrus for providing
  [`servant-swagger-ui`](https://hackage.haskell.org/package/servant-swagger-ui) library\non
  which this package is based on. \nThanks to David Johnson, Nickolay Kudasov, Maxim
  Koltsov authors of [`openapi3`](https://hackage.haskell.org/package/openapi3)\nand
  [`servant-openapi3`](https://hackage.haskell.org/package/servant-openapi3) libraries.
  The mapping from Mig's Api to OpenApi \nis based on those packages.\n"
description-type: markdown
hash: 627eabd3a6438a75b0342119a86d7e1ca27fbb921b933881930570e496b557a8
homepage: https://github.com/anton-k/mig#readme
latest: 0.1.0.1
license-name: BSD-3-Clause
maintainer: anton.kholomiov@gmail.com
synopsis: Swagger servers for mig library
test-bench-deps: {}
