all-versions:
- 0.1.0.0
- 0.1.0.1
author: Danil Berestov
basic-deps:
  aeson: '>=0'
  base: '>=4.16 && <5'
  blaze-html: '>=0'
  blaze-markup: '>=0'
  bytestring: '>=0'
  case-insensitive: '>=0'
  directory: '>=0'
  file-embed-lzma: '>=0'
  filepath: '>=0'
  http-api-data: '>=0'
  http-types: '>=0'
  insert-ordered-containers: '>=0'
  lens: '>=0'
  minion: '>=0'
  openapi3: '>=0'
  template-haskell: '>=0'
  text: '>=0'
changelog: |-
  # 0.1.0.1
  -- fixed build, added
changelog-type: markdown
description: "# Minion\n\nMinion is Haskell library for developing web applications.
  It stands between [Scotty](https://hackage.haskell.org/package/scotty) and [Servant](https://hackage.haskell.org/package/servant-server)
  \ \n\n|                  | Scotty | Minion | Servant |\n| ---------------- | ------
  | ------ | ------- |\n| As simple as ABC | Yes    | No     | No      |\n| At term
  level    | Yes    | Yes    | No      |\n| Typesafe         | No     | Yes    | Yes
  \    |\n| Introspectable   | No     | Yes    | Yes     |\n| Generated client | No
  \    | No     | Yes     |\n\n  \nSince Minion defines servers at the term level,
  it's easier to start and without excess verbosity.\n\n```haskell\n{-# LANGUAGE OverloadedStrings
  #-}\n{-# LANGUAGE OverloadedLists #-}\nmodule Main where\n\nimport Web.Minion\nimport
  Network.Wai.Handler.Warp qualified as Warp\n\nmain :: IO ()\nmain = Warp.run 9001
  app\n\napp :: ApplicationM IO\napp = serve api \n\napi :: Router Void IO\napi =
  \"api\" /> \n    [ \"about\" /> handlePlainText @String GET (pure \"Hello-World
  Minion server\")\n    , \"hello\" /> capture @String \"name\" \n              .>
  handlePlainText @String GET (\\name -> pure $ \"Hello, \" <> name <> \"!\")\n    ]\n```\n\nDocumentation
  and examples can be found on [Hackage](https://hackage.haskell.org/package/minion)
  \ \n\nMinion ecosystem also contains following libraries:\n* [minion-conduit](https://hackage.haskell.org/package/minion-conduit)
  \n* [minion-htmx](https://hackage.haskell.org/package/minion-htmx) \n* [minion-jwt](https://hackage.haskell.org/package/minion-jwt)
  \n* [minion-wai-extra](https://hackage.haskell.org/package/minion-wai-extra) \n*
  [minion-openapi3](https://hackage.haskell.org/package/minion-openapi3) "
description-type: markdown
hash: 1628d7254fe5e38f01bde1bc1c66ffca3016fa18c4e83c7c2002b5e69ab1d20b
homepage: ''
latest: 0.1.0.1
license-name: MIT
maintainer: goosedb@yandex.ru
synopsis: Minion openapi3 support
test-bench-deps: {}
