all-versions:
- 0.1.0.0
author: ''
basic-deps:
  aeson: '>=0'
  base: <4.15
  deriving-aeson: '>=0'
  lens: '>=0'
  openapi3: '>=0'
  text: '>=0'
changelog: |
  # 0.1.0.0

  Initial release
changelog-type: markdown
description: DerivingVia for OpenAPI 3
description-type: haddock
hash: 3f6bd4e57c4252b17333ca51b964e57ba123f0a3d1c8c4359a5b82e1baefef34
homepage: https://github.com/ilyakooo0/deriving-openapi3#readme
latest: 0.1.0.0
license-name: MIT
maintainer: Ilya Kostyuchenko <ilyakooo0@gmail.com>
synopsis: DerivingVia for OpenAPI 3
test-bench-deps: {}
