homepage: https://github.com/ilyakooo0/deriving-openapi3#readme
changelog-type: markdown
hash: 3f6bd4e57c4252b17333ca51b964e57ba123f0a3d1c8c4359a5b82e1baefef34
test-bench-deps: {}
maintainer: Ilya Kostyuchenko <ilyakooo0@gmail.com>
synopsis: DerivingVia for OpenAPI 3
changelog: |
  # 0.1.0.0

  Initial release
basic-deps:
  base: <4.15
  text: -any
  lens: -any
  deriving-aeson: -any
  openapi3: -any
  aeson: -any
all-versions:
- 0.1.0.0
author: ''
latest: 0.1.0.0
description-type: haddock
description: DerivingVia for OpenAPI 3
license-name: MIT
