homepage: https://github.com/ilyakooo0/deriving-openapi3#readme
changelog-type: markdown
hash: 63513057f662e9dfdf8f9c76ec36a6a13fb11c9d04ddaef5f051a605f9b44006
test-bench-deps: {}
maintainer: Ilya Kostyuchenko <ilyakooo0@gmail.com>
synopsis: DerivingVia for OpenAPI 3
changelog: |
  # 0.1.0.0

  Initial release
basic-deps:
  base: <4.15
  text: <1.3
  lens: <4.20
  deriving-aeson: <0.3
  openapi3: <3.2
  aeson: <1.6
all-versions:
- 0.1.0.0
author: ''
latest: 0.1.0.0
description-type: haddock
description: DerivingVia for OpenAPI 3
license-name: MIT
