all-versions:
- 0.1.0.6
author: Karun Ramakrishnan, Ricky Elrod
basic-deps:
  base: '>=4 && <5'
  bytestring: '>=0.10 && <0.11'
  configurator: '>=0.3 && <0.4'
  directory: '>=1.1 && <1.3'
  doctest: '>=0.9'
  filepath: '>=1.2 && <1.4'
changelog: ''
changelog-type: ''
description: doctest-discover provides an easy way to run doctests via cabal (uses
  configurator instead of aeson)
description-type: haddock
hash: 79f62a00ff10acba4f850730ed2ffe99d5637bdfdb48f6fc4b92f03fbbb20a45
homepage: http://github.com/relrod/doctest-discover-noaeson
latest: 0.1.0.6
license-name: LicenseRef-PublicDomain
maintainer: ricky@elrod.me
synopsis: Easy way to run doctests via cabal (no aeson dependency, uses configurator
  instead)
test-bench-deps:
  base: '>4 && <5'
  doctest: '>=0'
  doctest-discover-configurator: '>=0'
