all-versions:
- 1.1.0
- 1.1.1
- 1.2.0
- 1.3.0
- 1.3.1
- 1.4.0
author: Raghu Kaippully
basic-deps:
  base: '>=4.17.0.0 && <4.22'
  bytestring: '>=0.11.0.0 && <0.13'
  file-embed: '>=0.0 && <0.1'
  http-types: '>=0.12 && <0.13'
  text: '>=2.0 && <2.2'
  wai-app-static: '>=3.1 && <3.2'
  webgear-core: ^>=1.4.0
changelog: |
  # Changelog for webgear-swagger-ui

  ## [Unreleased]

  ## [1.4.0] - 2025-05-19

  ### Added
  - Support GHC-9.12

  ### Removed
  - Support GHC-9.0, GHC-9.2

  ## [1.3.1] - 2024-11-24

  ### Added
  - Support GHC-9.10

  ## [1.3.0] - 2024-06-13

  ### Changed
  - Simplify core API (breaking change) (#47)

  ## [1.2.0] - 2024-03-18

  ### Changed
  - Support for embedding WAI applications in handlers (#36)

  ## [1.1.1] - 2024-01-01

  ### Changed
  - Updated dependency bounds and GHC versions (#35)

  ## [1.1.0] - 2023-12-29

  ### Added
  - First version of webgear-swagger-ui

  [Unreleased]: https://github.com/haskell-webgear/webgear/compare/v1.4.0...HEAD
  [1.4.0]: https://github.com/haskell-webgear/webgear/releases/tag/v1.4.0
  [1.3.1]: https://github.com/haskell-webgear/webgear/releases/tag/v1.3.1
  [1.3.0]: https://github.com/haskell-webgear/webgear/releases/tag/v1.3.0
  [1.2.0]: https://github.com/haskell-webgear/webgear/releases/tag/v1.2.0
  [1.1.1]: https://github.com/haskell-webgear/webgear/releases/tag/v1.1.1
  [1.1.0]: https://github.com/haskell-webgear/webgear/releases/tag/v1.1.0
changelog-type: markdown
description: |
  # WebGear - Swagger UI

  [![Hackage](https://img.shields.io/hackage/v/webgear-swagger-ui)](https://hackage.haskell.org/package/webgear-swagger-ui)

  WebGear is a Haskell library for building composable, type-safe HTTP APIs. This package helps to serve swagger UI based
  on WebGear API specifications.

  # License
  This package is released under [Mozilla Public License 2.0](./LICENSE). It also embeds an unmodified copy of
  [swagger-ui-dist](https://github.com/swagger-api/swagger-ui) released under [Apache License
  2.0](https://github.com/swagger-api/swagger-ui/blob/master/LICENSE).
description-type: markdown
hash: 98d6880c26f4eb28bd47036f439bb9692f6903832c2c212db0e6e2667f188204
homepage: https://github.com/haskell-webgear/webgear#readme
latest: 1.4.0
license-name: MPL-2.0
maintainer: rkaippully@gmail.com
synopsis: Host swagger UI based on WebGear API specifications.
test-bench-deps: {}
