all-versions:
- 1.1.0
- 1.1.1
author: Raghu Kaippully
basic-deps:
  base: '>=4.13.0.0 && <4.19'
  bytestring: '>=0.10.10.1 && <0.13'
  file-embed: '>=0.0 && <0.1'
  http-types: '>=0.12 && <0.13'
  mime-types: '>=0.1 && <0.2'
  text: '>=1.2.0.0 && <2.2'
  webgear-core: ^>=1.1.1
changelog: |
  # Changelog for webgear-swagger-ui

  ## [Unreleased]

  ## [1.1.1] - 2024-01-01

  ### Changed
  - Updated dependency bounds and GHC versions (#35)

  ## [1.1.0] - 2023-12-29

  ### Added
  - First version of webgear-swagger-ui

  [Unreleased]: https://github.com/haskell-webgear/webgear/compare/v1.1.1...HEAD
  [1.1.1]: https://github.com/haskell-webgear/webgear/releases/tag/v1.1.1
  [1.1.0]: https://github.com/haskell-webgear/webgear/releases/tag/v1.1.0
changelog-type: markdown
description: |
  # WebGear - Swagger UI

  [![Hackage](https://img.shields.io/hackage/v/webgear-swagger-ui)](https://hackage.haskell.org/package/webgear-swagger-ui)

  WebGear is a Haskell library for building composable, type-safe HTTP APIs. This package helps to serve swagger UI based
  on WebGear API specifications.

  # License
  This package is released under [Mozilla Public License 2.0](./LICENSE). It also embeds an unmodified copy of
  [swagger-ui-dist](https://github.com/swagger-api/swagger-ui) released under [Apache License
  2.0](https://github.com/swagger-api/swagger-ui/blob/master/LICENSE).
description-type: markdown
hash: 7e1b9c697c253a7aabcb49e10a2172d358bdf72709cecd57ce69f2b1772907e2
homepage: https://github.com/haskell-webgear/webgear#readme
latest: 1.1.1
license-name: MPL-2.0
maintainer: rkaippully@gmail.com
synopsis: Host swagger UI based on WebGear API specifications.
test-bench-deps: {}
