all-versions:
- '0.1'
- '0.2'
- 0.2.1
- 0.2.2
- 0.3.0
author: Toralf Wittner
basic-deps:
  aeson: '>=0.6'
  base: '>=4.6 && <5.0'
  bytestring: '>=0.10.4'
  text: '>=0.11'
  time: '>=1.4'
  transformers: '>=0.3'
changelog: ''
changelog-type: ''
description: |-
  Implementation of Swagger specification version 1.2 as defined in
  <https://github.com/wordnik/swagger-spec/blob/master/versions/1.2.md>
description-type: haddock
hash: ecabd501ebebd2a344ed21f01adfa598fbe41d40c0619d04aaa611815b659006
homepage: ''
latest: 0.3.0
license-name: LicenseRef-OtherLicense
maintainer: Toralf Wittner <tw@dtex.org>
synopsis: Implementation of swagger data model
test-bench-deps:
  aeson: '>=0'
  base: '>=0'
  bytestring: '>=0'
  swagger: '>=0'
  tasty: '>=0.8'
  tasty-hunit: '>=0.8'
