homepage: https://github.com/NorfairKing/autodocodec#readme
changelog-type: markdown
hash: 86e2f867bf491fc36daff3ee39870027bc398e309fca16907be30a5db835257a
test-bench-deps: {}
maintainer: syd@cs-syd.eu
synopsis: Autodocodec interpreters for openapi3
changelog: |
  # Changelog

  ## [0.0.0.0] - 2021-11-19

  First release.
basic-deps:
  insert-ordered-containers: -any
  base: '>=4.7 && <5'
  text: -any
  openapi3: -any
  autodocodec: -any
  scientific: -any
  aeson: -any
all-versions:
- 0.0.0.0
author: Tom Sydney Kerckhove
latest: 0.0.0.0
description-type: haddock
description: ''
license-name: MIT
