homepage: https://github.com/NorfairKing/autodocodec#readme
changelog-type: markdown
hash: 1a59f571a2ed45d2793214cdfe8d81f795896cdba803d3e43acc950acf7df9a4
test-bench-deps: {}
maintainer: syd@cs-syd.eu
synopsis: Autodocodec interpreters for openapi3
changelog: |
  # Changelog

  ## [0.1.0.0] - 2021-12-23

  ### Added

  * `disjointEitherCodec` now no longer generates `additionalProperties = true` and uses `oneOf` instead of `anyOf`.

  ### Changed

  * Now uses `nullable: true` instead of `anyOf` for maybe codecs.

  ## [0.0.0.0] - 2021-11-19

  First release.
basic-deps:
  insert-ordered-containers: -any
  base: '>=4.7 && <5'
  text: -any
  lens: -any
  openapi3: -any
  autodocodec: -any
  scientific: -any
  aeson: -any
all-versions:
- 0.0.0.0
- 0.1.0.0
author: Tom Sydney Kerckhove
latest: 0.1.0.0
description-type: haddock
description: ''
license-name: MIT
