homepage: https://github.com/NorfairKing/autodocodec#readme
changelog-type: markdown
hash: 93461f7233e3a5beb114d757ba9165720f0fd94ca3a0e279c13207949df34271
test-bench-deps: {}
maintainer: syd@cs-syd.eu
synopsis: Autodocodec interpreters for swagger2
changelog: |
  # Changelog

  ## [0.0.1.1] - 2022-07-21

  ### Added

  * Support for the `discriminatedUnionCodec` for discriminated unions in `autodocodec-0.2.0.0`

  ## [0.0.1.0] - 2021-11-19

  ### Added

  * `disjointEitherCodec` now does not generate `additionalProperties = true`.

  ## [0.0.0.0] - 2021-11-19

  First release.
basic-deps:
  insert-ordered-containers: -any
  base: '>=4.7 && <5'
  unordered-containers: -any
  text: -any
  autodocodec: '>=0.2.0.0'
  swagger2: -any
  scientific: -any
  aeson: -any
all-versions:
- 0.0.0.0
- 0.0.1.0
- 0.0.1.1
author: Tom Sydney Kerckhove
latest: 0.0.1.1
description-type: haddock
description: ''
license-name: MIT
