homepage: https://github.com/NorfairKing/autodocodec#readme
changelog-type: markdown
hash: 617f5af49bb6a1f0b0f192a84f13dad3cb901a2c6951597ce1dfbaad41dab049
test-bench-deps: {}
maintainer: syd@cs-syd.eu
synopsis: Autodocodec interpreters for swagger2
changelog: |
  # Changelog

  ## [0.0.0.0] - 2021-11-19

  First release.
basic-deps:
  insert-ordered-containers: -any
  base: '>=4.7 && <5'
  text: -any
  autodocodec: -any
  swagger2: -any
  scientific: -any
  aeson: -any
all-versions:
- 0.0.0.0
author: Tom Sydney Kerckhove
latest: 0.0.0.0
description-type: haddock
description: ''
license-name: MIT
