homepage: https://github.com/NorfairKing/autodocodec#readme
changelog-type: markdown
hash: 6e04a94907fec9a6b00dd0b00c6b098e7807b85210f179ee9d807c613ef216ba
test-bench-deps: {}
maintainer: syd@cs-syd.eu
synopsis: Autodocodec interpreters for swagger2
changelog: |
  # Changelog

  ## [0.0.1.0] - 2021-11-19

  ### Added

  * `disjointEitherCodec` now does not generate `additionalProperties = true`.

  ## [0.0.0.0] - 2021-11-19

  First release.
basic-deps:
  insert-ordered-containers: -any
  base: '>=4.7 && <5'
  text: -any
  autodocodec: '>=0.0.1.0'
  swagger2: -any
  scientific: -any
  aeson: -any
all-versions:
- 0.0.0.0
- 0.0.1.0
author: Tom Sydney Kerckhove
latest: 0.0.1.0
description-type: haddock
description: ''
license-name: MIT
