all-versions:
- 0.0.0.0
- 0.0.1.0
- 0.0.1.1
- 0.0.1.2
author: Tom Sydney Kerckhove
basic-deps:
  aeson: '>=0'
  autodocodec: '>=0.3.0.0'
  base: '>=4.7 && <5'
  insert-ordered-containers: '>=0'
  scientific: '>=0'
  swagger2: '>=0'
  text: '>=0'
  unordered-containers: '>=0'
changelog: |
  # Changelog

  ## [0.0.1.1] - 2022-07-21

  ### Added

  * Support for the `discriminatedUnionCodec` for discriminated unions in `autodocodec-0.2.0.0`

  ## [0.0.1.0] - 2021-11-19

  ### Added

  * `disjointEitherCodec` now does not generate `additionalProperties = true`.

  ## [0.0.0.0] - 2021-11-19

  First release.
changelog-type: markdown
description: ''
description-type: haddock
hash: 56fe81940b93d6f88ad502a022acd0ba61fdf4a6229fda32e0488c14555a0681
homepage: https://github.com/NorfairKing/autodocodec#readme
latest: 0.0.1.2
license-name: MIT
maintainer: syd@cs-syd.eu
synopsis: Autodocodec interpreters for swagger2
test-bench-deps: {}
