all-versions:
- 1.0.0.0
author: David Luposchainsky, effectfully
basic-deps:
  base: '>=4.9 && <5'
  microlens: '>=0'
  mtl: '>=0'
  prettyprinter: '>=0'
  text: '>=0'
changelog: ''
changelog-type: ''
description: |
  # `prettyprinter-configurable`

  This is a version of the [`prettyprinter`](https://hackage.haskell.org/package/prettyprinter) library that makes pretty-printing configurable. I regret writing it the way I did, so you probably don't want to use it.
description-type: markdown
hash: 5d5ab764910f511a2d4d0907074e44eadec3e7622553e739401c67277d1e5bb6
homepage: https://github.com/effectfully/prettyprinter-configurable
latest: 1.0.0.0
license-name: Apache-2.0
maintainer: effectfully@gmail.com
synopsis: Configurable pretty-printing
test-bench-deps:
  QuickCheck: '>=0'
  base: '>=4.9 && <5'
  megaparsec: '>=0'
  parser-combinators: '>=0'
  prettyprinter-configurable: '>=0'
  quickcheck-text: '>=0'
  tasty: '>=0'
  tasty-hunit: '>=0'
  tasty-quickcheck: '>=0'
  text: '>=0'
