all-versions:
- 0.1.0.0
author: Eric Torreborre
basic-deps:
  base: '>=4.7 && <5'
changelog: ''
changelog-type: ''
description: |
  ![Build status](https://travis-ci.org/etorreborre/producer-hs.svg?branch=master)

  # Producer

  Simple streaming library for Haskell
description-type: markdown
hash: f882d20a654d06bbd57c692d8c433c1fee11d0f3a285a45330d459c437b3531b
homepage: https://github.com/etorreborre/producer-hs#readme
latest: 0.1.0.0
license-name: MIT
maintainer: etorreborre@yahoo.com
synopsis: Simple streaming datatype
test-bench-deps:
  QuickCheck: '>=0'
  base: '>=0'
  checkers: '>=0'
  producer: '>=0'
  tasty: '>=0'
  tasty-auto: '>=0'
  tasty-hunit: '>=0'
  tasty-quickcheck: '>=0'
