all-versions:
- 0.1.0.0
author: Lucas DiCioccio
basic-deps:
  aeson: '>=2.2.1 && <2.3'
  base: '>=4.19.1 && <4.20'
  bytestring: '>=0.12.1 && <0.13'
  containers: '>=0.6.8 && <0.7'
  http-client: '>=0.7.17 && <0.8'
  http-reverse-proxy: '>=0.6.0 && <0.7'
  http-types: '>=0.12.4 && <0.13'
  prodapi: '>=0.1.0 && <0.2'
  prometheus-client: '>=1.1.1 && <1.2'
  random-shuffle: '>=0.0.4 && <0.1'
  servant: '>=0.20.1 && <0.21'
  servant-server: '>=0.20 && <0.21'
  text: '>=2.1.1 && <2.2'
  time: '>=1.12.2 && <1.13'
  tls: '>=2.0.5 && <2.1'
  wai: '>=3.2.4 && <3.3'
  warp-tls: '>=3.4.5 && <3.5'
changelog: |
  # Revision history for prodapi-userauth

  ## 0.1.0.0 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
changelog-type: markdown
description: a library to write loadbalancers compatible with prodapi discovery and
  healthchecks
description-type: haddock
hash: 20164b90c57bfc99671f0751da59b96619de532633ff09e9cc1c946ee56abd8d
homepage: ''
latest: 0.1.0.0
license-name: BSD-3-Clause
maintainer: lucas@dicioccio.fr
synopsis: write an HTTP proxy with prodapi counters
test-bench-deps: {}
