all-versions:
- 0.1.0.0
author: M Farkas-Dyck
basic-deps:
  base: '>=4.10 && <5'
  category: '>=0'
changelog: ''
changelog-type: ''
description: ''
description-type: haddock
hash: a2cabd32048d2e655101d0687d9a44f2f20eaf4ec423957df1020e8698174d6b
homepage: ''
latest: 0.1.0.0
license-name: BSD-3-Clause
maintainer: None
synopsis: Product category
test-bench-deps: {}
