homepage: ''
changelog-type: ''
hash: f5dd4b5e37a81e4d7d1645f5d6e3edb46bb1468a71cbf33e5ee70ca8c3e3b3ac
test-bench-deps: {}
maintainer: m.farkasdyck@gmail.com
synopsis: Product category
changelog: ''
basic-deps:
  base: ! '>=4.10 && <5'
  category: -any
all-versions:
- '0.1.0.0'
author: M Farkas-Dyck
latest: '0.1.0.0'
description-type: haddock
description: ''
license-name: BSD3
