all-versions:
- 0.0.1.0
- 0.0.2.0
- 0.0.3.0
- 0.0.3.1
- 0.0.3.2
- 0.0.3.3
- 0.0.3.4
author: Kei Hibino
basic-deps:
  base: '>=4.5 && <5'
  template-haskell: '>=0'
  th-data-compat: '>=0.1.3'
changelog: ''
changelog-type: ''
description: |-
  Weaken applicative functor which allows only product
  construction. Product constructions and deconstructions
  are always isomorphic.
description-type: haddock
hash: 91be6bcf7db25d4a9129fe7a4624a48e1f94d0acad2505d25941b0ccd4e52497
homepage: http://github.com/khibino/haskell-product-isomorphic
latest: 0.0.3.4
license-name: BSD-3-Clause
maintainer: ex8k.hibino@gmail.com
synopsis: Weaken applicative functor on products
test-bench-deps:
  base: <5
  product-isomorphic: '>=0'
  template-haskell: '>=0'
