all-versions:
- 0.1.0.0
author: Lucas DiCioccio
basic-deps:
  aeson: '>=2.2.1 && <2.3'
  async: '>=2.2.5 && <2.3'
  base: '>=4.7 && <5'
  bytestring: '>=0.12.1 && <0.13'
  containers: '>=0.6.8 && <0.7'
  contravariant: '>=1.5.5 && <1.6'
  directory: '>=1.3.8 && <1.4'
  http-api-data: '>=0.6 && <0.7'
  http-client: '>=0.7.17 && <0.8'
  http-media: '>=0.8.1 && <0.9'
  lucid: '>=2.11.20230408 && <2.12'
  process-extras: '>=0.7.4 && <0.8'
  prometheus-client: '>=1.1.1 && <1.2'
  prometheus-metrics-ghc: '>=1.0.1 && <1.1'
  servant: '>=0.20.1 && <0.21'
  servant-client: '>=0.20 && <0.21'
  servant-server: '>=0.20 && <0.21'
  text: '>=2.1.1 && <2.2'
  time: '>=1.12.2 && <1.13'
  uuid: '>=1.3.15 && <1.4'
  wai: '>=3.2.4 && <3.3'
changelog: |
  # Revision history for prodapi

  ## 0.1.0.0 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
changelog-type: markdown
description: A library of curated and opinionated packages for building Haskell serivces,
  with some preferred pattern. Services expose metrics using prometheus and log events
  via contravariant logging.
description-type: haddock
hash: ff6288b84fa95f74208d63dc3dfa222766b1fd07cb262b01dff60a3a97394377
homepage: ''
latest: 0.1.0.0
license-name: BSD-3-Clause
maintainer: lucas@dicioccio.fr
synopsis: Some curated and opinionated packages for building Haskell services.
test-bench-deps: {}
