all-versions:
- 0.1.0.0
author: Lucas DiCioccio
basic-deps:
  aeson: '>=2.2.1 && <2.3'
  base: '>=4.19.1 && <4.20'
  bytestring: '>=0.12.1 && <0.13'
  containers: '>=0.6.8 && <0.7'
  cookie: '>=0.4.6 && <0.5'
  http-api-data: '>=0.6 && <0.7'
  jwt: '>=0.11.0 && <0.12'
  lucid: '>=2.11.20230408 && <2.12'
  postgresql-simple: '>=0.7.0 && <0.8'
  prodapi: '>=0.1.0 && <0.2'
  prometheus-client: '>=1.1.1 && <1.2'
  servant: '>=0.20.1 && <0.21'
  servant-server: '>=0.20 && <0.21'
  text: '>=2.1.1 && <2.2'
  time: '>=1.12.2 && <1.13'
  uuid: '>=1.3.15 && <1.4'
  wai: '>=3.2.4 && <3.3'
changelog: |
  # Revision history for prodapi-userauth

  ## 0.1.0.0 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
changelog-type: markdown
description: implements basic bricks for password, oauth2 authentification of user
  identities
description-type: haddock
hash: ff37839b1268612f8b905dcf0b9f82b10b97e95576d6eafa0313a92651d3c2b9
homepage: ''
latest: 0.1.0.0
license-name: BSD-3-Clause
maintainer: lucas@dicioccio.fr
synopsis: a base lib for performing user-authentication in prodapi services
test-bench-deps: {}
