homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: markdown
hash: 6ed3d7cd05a61883f22dae7ff9566166b0504d9cc07a5040195bd41bab61c556
test-bench-deps:
  base: ==4.*
  criterion: -any
  product-profunctors: -any
  deepseq: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: |
  # 0.11.1.1

  * No user-visible changes

  # 0.11.1.0

  * Generalise `(***$)` to work on `Profunctor` instead of `ProductProfunctor`.
  * `instance Monoid r => ProductProfunctor (Forget r)`
  * `instance SumProfunctor (Forget r)`

  # 0.11.0.3

  * Support GHC 9.2

  # 0.11.0.2

  * Support GHC 9.0

  # 0.11.0.0

  * Added `makeAdaptorAndInstanceInferrable` which has better inference
    properties, at the cost having to turn on `UndecidableInstances`.
    The tuple instances are now made by this method too.

    Please note that if you have written your own `Default` instances
    containing tuples they will no longer work, or may break in
    unexpected ways.  For example, the following are no longer supported

    ```haskell
    instance Default MyProfunctor (Foo, Bar) Baz
    instance Default MyProfunctor Foo,  (Bar, Baz)
    ```

  # 0.10.0.1

  * Added `Data.Profunctor.Product.Examples`

  # 0.10.0.0

  * Removed `ProductContravariant`, `AndArrow`, `defaultContravariantProduct`,
    `PPOfContravariant`, `unPPOfContravariant`, `cdef`

  * Deprecated `defaultEmpty`, `defaultProfunctorProduct`, `defaultPoint`

  # 0.9.0.0

  * Added more `ProductProfunctor/SumProfunctor` instances including for
    types in `Data.Bifunctor`

  * Added `Data.Profunctor.Product.Adaptor` which derives
    `genericAdaptor` with `Generic`

  * Added ability to derive `Default` instance with `Generic`

  Sorry, we didn't track changes before version 0.9.0.0
basic-deps:
  base: '>=4.5 && <4.19'
  th-abstraction: '>=0.4 && <0.5'
  tagged: '>=0.0 && <1'
  bifunctors: '>=5.4 && <6.0'
  contravariant: '>=0.4 && <1.6'
  template-haskell: <2.21
  profunctors: '>=5 && <5.7'
all-versions:
- '0.5'
- '0.6'
- 0.6.1
- 0.6.3
- 0.6.3.1
- 0.7.0.2
- 0.7.1.0
- 0.8.0.2
- 0.8.0.3
- 0.9.0.0
- 0.10.0.0
- 0.10.0.1
- 0.11.0.0
- 0.11.0.1
- 0.11.0.2
- 0.11.0.3
- 0.11.1.0
- 0.11.1.1
author: Purely Agile
latest: 0.11.1.1
description-type: markdown
description: |
  # product-profunctors [![Hackage version](https://img.shields.io/hackage/v/product-profunctors.svg?label=Hackage)](https://hackage.haskell.org/package/product-profunctors) [![Build status](https://img.shields.io/github/workflow/status/tomjaguarpaw/product-profunctors/ci/master.svg)](https://github.com/tomjaguarpaw/product-profunctors/actions)

  ## Backup maintainers

  In the event of the main developer becoming unreachable, please
  contact the following who are authorised to make bugfixes and
  dependency version bumps:

  * Adam Bergmark
  * Erik Hesselink
  * Oliver Charles
license-name: BSD-3-Clause
