homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: markdown
hash: cad35a8001a2a8bc3d9c9c27bd99ac100b2e0d64140ad54a4cce9ff71d1af19f
test-bench-deps:
  base: ==4.*
  criterion: -any
  product-profunctors: -any
  deepseq: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: ! "# 0.10.0.0\n\n* Removed `ProductContravariant`, `AndArrow`, `defaultContravariantProduct`,\n
  \ `PPOfContravariant`, `unPPOfContravariant`, `cdef`\n\n* Deprecated `defaultEmpty`,
  `defaultProfunctorProduct`, `defaultPoint`\n\n# 0.9.0.0\n\n* Added more `ProductProfunctor/SumProfunctor`
  instances including for\n  types in `Data.Bifunctor`\n\n* Added `Data.Profunctor.Product.Adaptor`
  which derives\n  `genericAdaptor` with `Generic`\n\n* Added ability to derive `Default`
  instance with `Generic`\n\nSorry, we didn't track changes before version 0.9.0.0\n"
basic-deps:
  base: ! '>=4.5 && <5'
  tagged: ! '>=0.0 && <1'
  bifunctors: ! '>=5.4 && <6.0'
  contravariant: ! '>=0.4 && <1.6'
  template-haskell: -any
  profunctors: ! '>=5 && <5.4'
all-versions:
- '0.5'
- '0.6'
- '0.6.1'
- '0.6.3'
- '0.6.3.1'
- '0.7.0.2'
- '0.7.1.0'
- '0.8.0.2'
- '0.8.0.3'
- '0.9.0.0'
- '0.10.0.0'
author: Purely Agile
latest: '0.10.0.0'
description-type: markdown
description: ! '# product-profunctors [![Hackage version](https://img.shields.io/hackage/v/product-profunctors.svg?label=Hackage)](https://hackage.haskell.org/package/product-profunctors)
  [![Linux Build Status](https://img.shields.io/travis/tomjaguarpaw/product-profunctors/master.svg?label=Linux%20build)](https://travis-ci.org/tomjaguarpaw/product-profunctors)


  ## Backup maintainers


  In the event of the main developer becoming unreachable, please

  contact the following who are authorised to make bugfixes and

  dependency version bumps:


  * Adam Bergmark

  * Erik Hesselink

  * Oliver Charles

'
license-name: BSD3
