all-versions:
- 1.0.0
- 1.1.0
author: Ollie Charles
basic-deps:
  base: '>=4.9 && <4.11'
  bytestring: '>=0'
  clock: '>=0'
  hashable: '>=1.2.4.0'
  http-types: '>=0.9.1'
  mtl: '>=0'
  prometheus-effect: '>=0'
  random: '>=0'
  retry: '>=0'
  safe-exceptions: '>=0'
  streaming: '>=0'
  streaming-bytestring: '>=0'
  streaming-utils: '>=0'
  streaming-wai: '>=0'
  text: '>=0'
  transformers: '>=0'
  unordered-containers: '>=0'
  vector: '>=0.11.0.0'
  vector-algorithms: '>=0'
  wai: '>=0'
  warp: '>=0'
changelog: "# 1.1.0\n\n- `Prometheus.GHC.ghcStats` now has the type `m (Maybe (IO
  ThreadId))`.\n  \n  This was changed to clarify what happens if GC stats aren't
  enabled, in which case you'll just get `Nothing` back.\n \n  Don't forget to actually
  run the stats collector thread though! For example,\n  \n  ```haskell\n  (startGhcStats,
  registry) <- buildRegistry ghcStats\n  for_ startGhcStats id\n  ```\n\t\n\t\n# 1.0.0\n\nInitial
  release.\n"
changelog-type: markdown
description: |-
  [Prometheus](https://prometheus.io) is an open-source systems monitoring and
  alerting toolkit originally built at SoundCloud. Since its inception in 2012,
  many companies and organizations have adopted Prometheus, and the project has a
  very active developer and user community. It is now a standalone open source
  project and maintained independently of any company. To emphasize this and
  clarify the project's governance structure, Prometheus joined the Cloud Native
  Computing Foundation in 2016 as the second hosted project after Kubernetes.

  This library provides a Haskell client to Prometheus. It supports:

  * The metric types __counter__, __gauge__ and __histogram__.
  * Publishing metrics over HTTP (via WAI middleware).
  * Pushing metrics to the Prometheus push gateway.
  * Labels, along with dynamic labels.
  * Instrumentation, both for internal Prometheus monitoring and GHC statistics.
description-type: haddock
hash: 9c7386da0ade7c12057dfd876c13405063122750631a501aaebbf9a0a677d357
homepage: https://github.com/ocharles/prometheus-effect
latest: 1.1.0
license-name: BSD-3-Clause
maintainer: ollie@ocharles.org.uk
synopsis: Instrument applications with metrics and publish/push to Prometheus
test-bench-deps:
  base: '>=0'
  criterion: '>=0'
  prometheus-effect: '>=0'
  text: '>=0'
  weigh: '>=0'
