all-versions:
- 0.0.1
- 1.0.0
- 1.0.1
- 1.0.1.1
- 1.0.1.2
- 1.1.0
- 1.1.0.1
- 1.1.0.2
- 1.1.1
- 1.1.1.1
- 1.1.2
- 1.2.0
- 1.2.0.1
- 1.2.0.2
- 1.2.0.3
- 1.2.0.4
- 1.2.0.5
- 1.2.0.6
- 1.2.0.7
author: Michael Snoyman <michael@snoyman.com>
basic-deps:
  base: '>=4 && <5'
  containers: '>=0.2'
  path-pieces: '>=0.1 && <0.2'
  template-haskell: '>=0'
  text: '>=0.5'
  vector: '>=0.8 && <0.11'
changelog: ''
changelog-type: ''
description: Provides an efficient routing system, a parser and TH code generation.
description-type: haddock
hash: 0d622fd91f5c82a3ae54849a9f55e15b39dcc6240f9f2119151362255cd7334e
homepage: http://www.yesodweb.com/
latest: 1.2.0.7
license-name: MIT
maintainer: Michael Snoyman <michael@snoyman.com>
synopsis: Efficient routing for Yesod. (deprecated)
test-bench-deps:
  HUnit: '>=1.2 && <1.3'
  base: '>=4.3 && <5'
  bytestring: '>=0'
  containers: '>=0'
  hspec: '>=1.3'
  path-pieces: '>=0'
  template-haskell: '>=0'
  text: '>=0.5'
  yesod-routes: '>=0'
