all-versions:
- 0.1.0
author: Murat Kasimov
basic-deps:
  base: '>=4 && <5'
  transformers: '>=0'
changelog: ''
changelog-type: markdown
description: Lightweight and fast streaming
description-type: haddock
hash: faddf28d504d6954b5036d68c7c2cf089c482d1e04abafe3b287f88b64d75dc9
homepage: https://github.com/iokasimov/pipeline
latest: 0.1.0
license-name: BSD-3-Clause
maintainer: Murat Kasimov <iokasimov.m@gmail.com>
synopsis: Continuation patterns
test-bench-deps: {}
