all-versions:
- 0.0.1
- 0.0.1.1
- '1.0'
- '1.1'
author: Andrey Mokhov, Neil Mitchell, Simon Peyton Jones
basic-deps:
  algebraic-graphs: '>=0.5 && <0.8'
  base: '>=4.7 && <5'
  containers: '>=0.6 && <0.7'
  extra: '>=1.5.3 && <1.8'
  filepath: '>=1.4.1.0 && <1.5'
  mtl: '>=2.2.1 && <2.4'
  random: '>=1.1 && <1.3'
  transformers: '>=0.5.2.0 && <0.7'
changelog: |
  # Change log

  ## 1.0

  The version published in ICFP 2018 paper "Build Systems à la Carte".
changelog-type: markdown
description: |
  # Build Systems à la Carte

  [![Hackage version](https://img.shields.io/hackage/v/build.svg?label=Hackage)](https://hackage.haskell.org/package/build) [![Build status](https://img.shields.io/github/actions/workflow/status/snowleopard/build/ci.yml?branch=main)](https://github.com/snowleopard/build/actions)

  This project provides an executable framework for developing and comparing build systems, viewing them as
  related points in landscape rather than as isolated phenomena. The code derives from the ICFP 2018 paper
  ["Build Systems à la Carte"](https://dl.acm.org/citation.cfm?id=3236774)
  ([PDF](https://dl.acm.org/ft_gateway.cfm?id=3236774)).

  ## Getting Started

  You may be interested to:

  * Run `stack test` to execute all the provided build systems on a very simple example.
  * Look at the [HTML documentation](https://hackage.haskell.org/package/build) of all modules for the last release,
    or generate it yourself using `stack haddock`.
  * Read the code, particularly [Build.System](src/Build/System.hs), which is the concrete implementation of
    all build systems.

  ## Related Material

  * Blog post [on the motivation behind the project](https://blogs.ncl.ac.uk/andreymokhov/cloud-and-dynamic-builds/).
  * Blog post [on the task abstraction](https://blogs.ncl.ac.uk/andreymokhov/the-task-abstraction/).
  * Blog post [reviewing how the paper was written](https://neilmitchell.blogspot.com/2018/07/inside-paper-build-systems-la-carte.html).
  * Talk [by Neil on this paper and Shake](https://ndmitchell.com/#shake_18_may_2018).
  * A talk on build systems
    [by Andrey](https://github.com/snowleopard/build/releases/download/icfp-final/build-systems-slides-andrey.pdf).
description-type: markdown
hash: 530488d4741cc893926a30c1d7028b8ac623dee5c20e24cba62cc9028b0fdb8f
homepage: https://github.com/snowleopard/build
latest: '1.1'
license-name: MIT
maintainer: 'Andrey Mokhov <andrey.mokhov@gmail.com>, github: @snowleopard'
synopsis: Build Systems à la Carte
test-bench-deps:
  base: '>=4.7 && <5'
  build: '>=0'
  containers: '>=0.6 && <0.7'
  extra: '>=1.5.3 && <1.8'
  mtl: '>=2.2.1 && <2.4'
  transformers: '>=0.5.2.0 && <0.7'
