all-versions:
- 0.0.1.0
- 0.0.2.0
- 0.0.3.0
- 0.0.4.0
- 0.0.5.0
- 0.0.6.0
author: phoityne.hs@gmail.com
basic-deps:
  aeson: '>=0'
  async: '>=0'
  async-pool: '>=0'
  base: '>=4.18 && <5'
  data-default: '>=0'
  directory: '>=0'
  fast-logger: '>=0'
  filepath: '>=0'
  lens: '>=0'
  monad-logger: '>=0'
  mtl: '>=0'
  pms-domain-model: '>=0'
  safe-exceptions: '>=0'
  text: '>=0'
  yaml: '>=0'
changelog: |
  # Revision history for pms-application-service

  ## 0.0.6.0 -- 2025-07-20

  * Added proc tool.

  ## 0.0.5.0 -- 2025-07-13

  * Added serial tool.

  ## 0.0.4.0 -- 2025-06-29

  * Added prompts interface.

  ## 0.0.3.0 -- 2025-06-22

  * Changed scriptsDir to toolsDir.

  ## 0.0.2.0 -- 2025-06-15

  * Added expected prompt string for use with `expect`.

  ## 0.0.1.0 -- 2025-05-31

  * First version.
changelog-type: markdown
description: "# pms-application-service\n\n[`pty-mcp-server`](https://github.com/phoityne/pty-mcp-server)
  is a multi-threaded application designed to handle multiple domain-specific tasks
  concurrently.  \n`pms-application-service` is one of its internal packages, responsible
  for coordinating core application logic and managing concurrent execution across
  threads.\n\nThis package interprets user-intent commands (parsed from JSON-RPC requests)
  and executes them within specific domain contexts.  \nIt bridges structured input
  from the UI layer with the infrastructure layer's effectful operations, ensuring
  that requests are processed in a deterministic and decoupled manner.\n\nIn addition
  to command dispatching, `pms-application-service` manages the lifecycle of domain-aware
  applications and supervises their execution threads.  \nIt provides the orchestration
  required to safely run multiple applications in parallel, maintaining responsiveness
  and isolation across concurrent tasks.\n\n---\n\n## Package Structure\n![Package
  Structure](https://raw.githubusercontent.com/phoityne/pms-application-service/main/docs/31-1.png)\n---\n\n##
  Module Structure\n![Module Structure](https://raw.githubusercontent.com/phoityne/pms-application-service/main/docs/31-2.png)\n\n\n---\n"
description-type: markdown
hash: 69ef189286f046305c5ceb50883426fb0b20d3a0a7530138b30ac14227356002
homepage: https://github.com/phoityne/pms-application-service
latest: 0.0.6.0
license-name: Apache-2.0
maintainer: phoityne.hs@gmail.com
synopsis: pms-application-service
test-bench-deps:
  async: '>=0'
  base: '>=4.18 && <5'
  data-default: '>=0'
  hspec: '>=0'
  hspec-discover: '>=0'
  lens: '>=0'
  monad-logger: '>=0'
  pms-application-service: '>=0'
  pms-domain-model: '>=0'
  stm: '>=0'
  unix: '>=0'
