all-versions:
- 0.1.0.0
author: Lars Kuhtz & Jon Sterling
basic-deps:
  aws: '>=0.11'
  aws-general: '>=0.2.2'
  aws-kinesis: '>=0.1.5'
  base: '>=4.7 && <5.0'
  base-unicode-symbols: '>=0'
  bytestring: '>=0.10.4.0'
  configuration-tools: '>=0.2.12'
  mtl: '>=2.1.3.1'
  text: '>=1.2.0.3'
  transformers: '>=0.4.2.0'
changelog: ''
changelog-type: ''
description: Configuration types, parsers & renderers for AWS services, using configuration-tools.
description-type: haddock
hash: 536eacac6f54fbeb3e823d5b751eaa8cf1bb45a69f1d0bf54bdbff6245eb93e9
homepage: ''
latest: 0.1.0.0
license-name: Apache-2.0
maintainer: jon@jonmsterling.com
synopsis: Configuration types, parsers & renderers for AWS services
test-bench-deps: {}
