all-versions:
- 0.1.0.0
- 0.2.0.0
- 0.3.0.0
- 0.4.0.0
- 0.5.0.0
- 0.6.0.0
- 0.7.0.0
- 0.8.0.0
- 0.8.1.0
- 0.8.2.0
- 0.8.3.0
- 0.8.3.1
- 0.8.4.0
- 0.8.4.1
- 0.8.4.2
- 0.9.0.0
author: James Candy
basic-deps:
  base: '>=4 && <=5'
  free: ==5.1
  mmorph: '>=1.0 && <1.1'
  mtl: '>=2.2'
  transformers: '>=0'
changelog: ''
changelog-type: ''
description: |
  Methods for composing monads.

  The I/O monad transformer, PlusMonad, and Linear modules are deprecated. Their use is discouraged. This package is now about automatic monad lifting; and includes a rigorous implementation of Luth and Ghani coproducts structured around the Free monad.
description-type: haddock
hash: 2b209190f13d49f6b1386a3ac34f35fbd877134d1f6412234c92183894331d05
homepage: ''
latest: 0.9.0.0
license-name: BSD-3-Clause
maintainer: jacinablackbox@yahoo.com
synopsis: Methods for composing monads.
test-bench-deps: {}
