all-versions:
- 0.1.0
author: Mike Ledger
basic-deps:
  base: <5
  openapi3: '>=0'
  optics: '>=0'
  records-edsl-core: '>=0.1.0 && <0.2'
  relude: '>=0'
  template-haskell: <2.24
changelog: ''
changelog-type: ''
description: See https://hackage.haskell.org/packages/records-edsl
description-type: haddock
hash: 6dc34f3c0c63202a63eab1f4e00e29556f08184dd53bfc9471561c827bc8e961
homepage: ''
latest: 0.1.0
license-name: MPL-2.0
maintainer: Mike Ledger <mike@quasimal.com>
synopsis: ToSchema deriving for records-edsl
test-bench-deps: {}
