homepage: ''
changelog-type: markdown
hash: c0161e9759e7e8e511848318a332d86a8f09b35e80a9e3d2cbd281a668926b32
test-bench-deps: {}
maintainer: jpgarcia@fing.edu.uy
synopsis: Abstraction to manage user defined Type Errors
changelog: |
  # Revision history for Require

  ## 0.5.3.0 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
basic-deps:
  base: '>=4.12 && <4.18'
all-versions:
- 0.6.0.0
- 0.7.0.0
- 0.7.0.1
- 0.7.0.2
author: Juan García-Garland
latest: 0.7.0.2
description-type: haddock
description: |-
  requirements is a framework to build user-defined type errors.
  Users condense the arguments of functions that can raise a
  domain-specific error into a curried data type, the operator.
  The Require constraint predicates over operators. Ill-formed
  operators require the Error operator.
license-name: GPL-3.0-only
