all-versions:
- 0.6.0.0
- 0.7.0.0
- 0.7.0.1
- 0.7.0.2
- 0.7.0.3
author: Juan García-Garland
basic-deps:
  base: '>=4.20 && <4.21'
changelog: |
  # Revision history for Require

  ## 0.5.3.0 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
changelog-type: markdown
description: |-
  requirements is a framework to build user-defined type errors.
  Users condense the arguments of functions that can raise a
  domain-specific error into a curried data type, the operator.
  The Require constraint predicates over operators. Ill-formed
  operators require the Error operator.
description-type: haddock
hash: 27c31f1407fff5f25e2feadb1d673f11a8d6c10295f8a7ae55d619bd2edf32e6
homepage: ''
latest: 0.7.0.3
license-name: GPL-3.0-only
maintainer: jpgarcia@fing.edu.uy
synopsis: Abstraction to manage user defined Type Errors
test-bench-deps: {}
