homepage: ''
changelog-type: markdown
hash: 486a6aa7a9522d44a96b610cf0d340600da4d94d221e08e45ab1830139d24c13
test-bench-deps: {}
maintainer: jpgarcia@fing.edu.uy
synopsis: Abstraction to manage user defined Type Errors
changelog: |
  # Revision history for Require

  ## 0.5.3.0 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
basic-deps:
  base: '>=4.12 && <4.18'
all-versions:
- 0.6.0.0
- 0.7.0.0
- 0.7.0.1
author: Juan García-Garland
latest: 0.7.0.1
description-type: haddock
description: |-
  requirements is a framework to build user-defined type errors.
  Users condense the arguments of functions that can raise a
  domain-specific error into a curried data type, the operator.
  The Require constraint predicates over operators. Ill-formed
  operators require the Error operator.
license-name: GPL-3.0-only
