homepage: https://github.com/AnthonySuper/jordan
changelog-type: markdown
hash: 3dc5aff1cdbd2d45a1dc0697749a680ef77d6d758d6bebb03201d5694296a6aa
test-bench-deps:
  bytestring: '>=0.10.8.1 && <0.12'
  base: '>=4.14.1 && <4.17'
  jordan-openapi: '>=0.2.0 && <=0.3'
  text: '>=1.2.3.0 && <1.3'
  jordan-servant: '>=0.1.0.0 && <0.2'
  servant-openapi3: '>=2.0 && <=2.1'
  servant: '>=0.18 && <0.20'
  lens: '>=4.17 && <5.2'
  jordan: '>=0.2.0.0 && <0.3'
  openapi3: '>=3.1.0 && <3.3'
  contravariant: '>=1.5.5 && <1.6'
  attoparsec: '>=0.14.1 && <0.15'
  transformers: '>=0.5.5 && <=0.7'
  scientific: '>=0.3.7 && <0.4'
  http-types: '>=0.12.2 && <0.13'
  http-media: '>=0.7 && <0.9'
maintainer: anthony@noided.media
synopsis: OpenAPI schemas for Jordan-Powered Servant APIs
changelog: |
  # Revision history for jordan-servant-openapi

  ## 0.1.0.0 -- 2022-07-04

  * First version. Provides basic orphan instances.
basic-deps:
  bytestring: '>=0.10.8.1 && <0.12'
  base: '>=4.14.1 && <4.17'
  jordan-openapi: '>=0.2.0 && <=0.3'
  text: '>=1.2.3.0 && <1.3'
  jordan-servant: '>=0.1.0.0 && <0.2'
  servant-openapi3: '>=2.0 && <=2.1'
  servant: '>=0.18 && <0.20'
  lens: '>=4.17 && <5.2'
  jordan: '>=0.2.0.0 && <0.3'
  openapi3: '>=3.1.0 && <3.3'
  contravariant: '>=1.5.5 && <1.6'
  attoparsec: '>=0.14.1 && <0.15'
  transformers: '>=0.5.5 && <=0.7'
  scientific: '>=0.3.7 && <0.4'
  http-types: '>=0.12.2 && <0.13'
  http-media: '>=0.7 && <0.9'
all-versions:
- 0.1.0.0
author: Anthony Super
latest: 0.1.0.0
description-type: haddock
description: |-
  Jordan Servant OpenAPI provides orphan instances to generate OpenAPI V3 documenation
  for Jordan-Powered Servant APIs.
license-name: MIT
