homepage: ''
changelog-type: markdown
hash: 4a0ca55e9c459e97fb0858d83e70da221dcf8c4c3e45a3384e08b06ee72f13f7
test-bench-deps:
  insert-ordered-containers: '>=0.2.5 && <0.3'
  optics-core: '>=0.4 && <0.5'
  bytestring: '>=0.10.12 && <0.12'
  base: '>=4.14.1 && <4.17'
  jordan-openapi: -any
  hspec: -any
  text: '>=1.2.4 && <1.3'
  containers: '>=0.6.2 && <0.7'
  jordan: '>=0.2.0.0 && <0.3'
  openapi3: '>=3.1.0 && <3.3'
  contravariant: '>=1.5.5 && <1.6'
  http-types: '>=0.12.2 && <0.13'
  aeson: '>=1.5.6 && <2.3'
maintainer: anthony@noided.media
synopsis: OpenAPI Definitions for Jordan, Automatically
changelog: |
  # Revision history for jordan-openapi

  ## 0.2.0.0 -- 2022-07-04

  * Updated library to be compatible with `jordan` version `0.2.0.0`
  * Added *lots* of documenation.

  ## 0.1.0.0 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
basic-deps:
  insert-ordered-containers: '>=0.2.5 && <0.3'
  optics-core: '>=0.4 && <0.5'
  bytestring: '>=0.10.12 && <0.12'
  base: '>=4.14.1 && <4.17'
  text: '>=1.2.4 && <1.3'
  containers: '>=0.6.2 && <0.7'
  jordan: '>=0.2.0.0 && <0.3'
  openapi3: '>=3.1.0 && <3.3'
  contravariant: '>=1.5.5 && <1.6'
  http-types: '>=0.12.2 && <0.13'
  aeson: '>=1.5.6 && <2.3'
all-versions:
- 0.1.0.0
- 0.2.0.0
author: Anthony Super
latest: 0.2.0.0
description-type: haddock
description: Automatic generation of documentation for Jordan-powered types.
license-name: MIT
