homepage: ''
changelog-type: markdown
hash: eafbc38247f12da1933e83ca0a50d414964f2d8734e9bb322c581462c1627565
test-bench-deps:
  insert-ordered-containers: '>=0.2.5 && <0.3'
  optics-core: '>=0.4 && <0.5'
  bytestring: '>=0.10.12 && <0.11'
  base: ^>=4.14.1.0
  jordan-openapi: -any
  hspec: -any
  text: '>=1.2.4 && <1.3'
  containers: '>=0.6.2 && <0.7'
  jordan: '>=0.1.0.0 && <0.2'
  openapi3: '>=3.1.0 && <3.2'
  contravariant: '>=1.5.5 && <1.6'
  aeson: '>=1.5.6 && <1.6'
maintainer: anthony@noided.media
synopsis: OpenAPI Definitions for Jordan, Automatically
changelog: |
  # Revision history for jordan-openapi

  ## 0.1.0.0 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
basic-deps:
  insert-ordered-containers: '>=0.2.5 && <0.3'
  optics-core: '>=0.4 && <0.5'
  bytestring: '>=0.10.12 && <0.11'
  base: ^>=4.14.1.0
  text: '>=1.2.4 && <1.3'
  containers: '>=0.6.2 && <0.7'
  jordan: '>=0.1.0.0 && <0.2'
  openapi3: '>=3.1.0 && <3.2'
  contravariant: '>=1.5.5 && <1.6'
  aeson: '>=1.5.6 && <1.6'
all-versions:
- 0.1.0.0
author: Anthony Super
latest: 0.1.0.0
description-type: haddock
description: ''
license-name: MIT
