all-versions:
- '0.1'
author: Scrive AB
basic-deps:
  base: <5
  bytestring: '>=0'
  data-default: '>=0'
  exceptions: '>=0.6'
  text: '>=0'
  transformers-base: '>=0'
  unjson: '>=0'
  utf8-string: '>=0'
  yaml: '>=0'
changelog: ''
changelog-type: ''
description: |
  # kontra-config [![Hackage version](https://img.shields.io/hackage/v/kontra-config.svg?label=Hackage)](https://hackage.haskell.org/package/kontra-config) [![Build Status](https://secure.travis-ci.org/scrive/kontra-config.svg?branch=master)](http://travis-ci.org/scrive/kontra-config)

  A library for reading JSON configuration files. Based on unjson.
description-type: markdown
hash: c4bd3f416488580ac7f42f00b1173249f92db3c8a4940beba5cb985f5eb9ee8f
homepage: https://github.com/scrive/kontra-config
latest: '0.1'
license-name: BSD-3-Clause
maintainer: Gracjan Polak <gracjan@scrive.com>, Jonathan Jouty <jonathan@scrive.com>,
  Mikhail Glushenkov <mikhail@scrive.com>
synopsis: JSON config file parsing based on unjson
test-bench-deps: {}
