all-versions:
- 0.1.0.0
- 1.0.0
- 1.0.0.1
author: Mike Ledger
basic-deps:
  aeson: '>=1.0.0.0 && <2.3'
  base: '>=4.16 && <5'
  openapi3: '>=3 && <4'
  primitive: '>=0.7.3.0'
  vector: '>=0.12.2.0'
changelog: |2

  0.1.0.1 - 2026-05-12
  ====================
  - Fix haddock rendering of examples
  - Call myself Mike Ledger and not Michael Ledger; just because I've been going
    by "Mike" for forever anyway, it's probably just confusing to have a mix of
    packages with differing names.

  0.1.0.0 - 2026-02-10
  ====================
  Export gtupleToJSON, gtupleToEncoding, gtupleParseJSON

  0.1.0.0 - 2026-01-28
  ====================
  Initial release
changelog-type: markdown
description: This package lets you derive ToJSON/FromJSON instances for record data-types
  that are encoded into tuples
description-type: haddock
hash: e827e1c01aeeb465e2efcd213339431203468fa57d37645b1a75044d430069ca
homepage: ''
latest: 1.0.0.1
license-name: MPL-2.0
maintainer: mike@quasimal.com
synopsis: Encode and decode Haskell records as JSON tuples
test-bench-deps:
  QuickCheck: '>=0'
  aeson: '>=0'
  aeson-openapi-record-as-tuple: '>=0'
  base: '>=0'
  bytestring: '>=0'
  generic-random: '>=0'
  hspec: '>=0'
