all-versions:
- 0.1.0.0
- 0.2.0.0
- 0.2.0.1
- 0.3.0.0
- 0.3.0.1
- 0.4.0.0
- 0.4.1.0
- 0.5.0.0
author: John Goerzen (2004-2014), David Farrell
basic-deps:
  base: '>4.8 && <5.0'
  containers: '>=0'
  mtl: '>=0'
  parsec: '>=0'
changelog: ''
changelog-type: ''
description: A fork of ConfigFile updated and reworked to export a more consistent
  API for the Polar Game Engine.
description-type: haddock
hash: 72c3083deae1303c724ab1f7874cce508cfa41aecc46e9bf3774b0b2cfed7e28
homepage: ''
latest: 0.5.0.0
license-name: BSD-3-Clause
maintainer: David Farrell <shokku.ra@gmail.com>
synopsis: Fork of ConfigFile for Polar Game Engine
test-bench-deps:
  HUnit: '>=0'
  MissingH: '>=1.0'
  base: '>4.8 && <5.0'
  containers: '>=0'
  mtl: '>=0'
  parsec: '>=0'
