all-versions:
- '0.10'
- 0.10.0.1
- '0.11'
author: Grant Monroe, Leon P Smith, Joey Adams
basic-deps:
  base: <5
changelog: |
  0.11
  ----

  * Require libpq >=14.12

  0.10.0.1
  --------

  * Fix issues in `configure` script

  0.10
  ----

  * Initial release
changelog-type: markdown
description: |-
  This is a binding to libpq: the C application
  programmer's interface to PostgreSQL. libpq is a
  set of library functions that allow client
  programs to pass queries to the PostgreSQL
  backend server and to receive the results of
  these queries.
description-type: haddock
hash: 019c5d83da0b4dc0b4487e0e868f2eed5efa25e0688f5cfc2ba8191a80e527aa
homepage: https://github.com/haskellari/postgresql-libpq
latest: '0.11'
license-name: BSD-3-Clause
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
synopsis: 'low-level binding to libpq: configure based provider'
test-bench-deps: {}
