all-versions:
- '0.10'
- '0.11'
author: Grant Monroe, Leon P Smith, Joey Adams
basic-deps:
  base: <5
changelog: |
  0.11
  ----

  * Require libpq >=14.12

  0.10
  ----

  * Initial release
changelog-type: markdown
description: |-
  This is a binding to libpq: the C application
  programmer's interface to PostgreSQL. libpq is a
  set of library functions that allow client
  programs to pass queries to the PostgreSQL
  backend server and to receive the results of
  these queries.
description-type: haddock
hash: 9d6edd8ee105cfe7145b138c8f8bf582cddbd13af36c4302aeff891003efdc6f
homepage: https://github.com/haskellari/postgresql-libpq
latest: '0.11'
license-name: BSD-3-Clause
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
synopsis: 'low-level binding to libpq: pkg-config based provider'
test-bench-deps: {}
