all-versions:
- '0.10'
author: Grant Monroe, Leon P Smith, Joey Adams
basic-deps:
  base: <5
changelog: |
  0.10
  ----

  * Initial release0.10
changelog-type: markdown
description: |-
  This is a binding to libpq: the C application
  programmer's interface to PostgreSQL. libpq is a
  set of library functions that allow client
  programs to pass queries to the PostgreSQL
  backend server and to receive the results of
  these queries.
description-type: haddock
hash: d69e1e6512908bd36bc56378ae7e1159fef53a4da445db2a7784be01e314a594
homepage: https://github.com/haskellari/postgresql-libpq
latest: '0.10'
license-name: BSD-3-Clause
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
synopsis: 'low-level binding to libpq: pkg-config based provider'
test-bench-deps: {}
