homepage: https://github.com/conal/TypeCompose
changelog-type: ''
hash: d0d23df29bdc56096affee2bd057f852a4a96b0df08d1415de414b570f911fbe
test-bench-deps: {}
maintainer: conal@conal.net
synopsis: Type composition classes & instances
changelog: ''
basic-deps:
  base: '>=4.9 && <4.16'
  base-orphans: '>=0.5'
all-versions:
- '0.0'
- '0.1'
- '0.3'
- '0.5'
- 0.5.1
- 0.6.0
- 0.6.1
- 0.6.2
- 0.6.3
- 0.6.4
- 0.6.6
- 0.6.7
- 0.6.8
- 0.7.0
- 0.8.0
- 0.8.3
- 0.9.0
- 0.9.1
- 0.9.3
- 0.9.4
- 0.9.5
- 0.9.6
- 0.9.7
- 0.9.8
- 0.9.9
- 0.9.10
- 0.9.11
- 0.9.12
- 0.9.13
- 0.9.14
author: Conal Elliott
latest: 0.9.14
description-type: haddock
description: |-
  TypeCompose provides some classes & instances for forms of type
  composition, as well as some modules who haven't yet found a home.

  Please see the project wiki page: <http://haskell.org/haskellwiki/TypeCompose>

  Copyright 2007-2012 by Conal Elliott; BSD3 license.
license-name: BSD-3-Clause
