all-versions:
- 0.1.0.0
- 0.1.0.1
- 0.1.0.2
author: Patrick Chilton
basic-deps:
  base: '>=4.8 && <5'
  bytestring: '>=0'
  dlist: '>=0'
  http-types: '>=0'
  insert-ordered-containers: '>=0'
  lens: '>=0'
  mtl: '>=0'
  solga: '>=0'
  swagger2: '>=2.1'
  text: '>=0'
  unordered-containers: '>=0'
changelog: ''
changelog-type: ''
description: Swagger generation for Solga
description-type: haddock
hash: 47c65ca98998a9e6bdd533a724f5ee3e0b886a283a152959cc9fe4c7875cd38f
homepage: https://github.com/chpatrick/solga
latest: 0.1.0.2
license-name: MIT
maintainer: chpatrick@gmail.com
synopsis: Swagger generation for Solga
test-bench-deps: {}
